alphagov/content-data-admin

- config/application.rb
- config/initializers/govuk_publishing_components.rb
- config/routes.rb
This allows us to see the app's own components (when built) and those from the shared gem at /component-guide
> Add component guide to app

- config/environments/production.rb
This should not be set to debug. There may be a problem with
govuk_app_config, but manually updating for now.
> Set log level on production to info

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/initializers/logstasher.rb
We are not seeing anything in Kibana.
This makes the log configuration consistent with content-performance-manager.
> add logstasher configuration

- config/environments/production.rb
We are having issues deploying the application in integration. They seem
to be related to permissions issues when logging
```
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /data/vhost/content-data-admin/releases/20180814135728/log/production.json.log
/data/vhost/content-data-admin/releases/20180814135728/config/environments/production.rb:4:in `new'
/data/vhost/content-data-admin/releases/20180814135728/config/environments/production.rb:4:in `block in <main>'
/data/vhost/content-data-admin/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:216:in `instance_eval'
/data/vhost/content-data-admin/shared/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:216:in `configure'
/data/vhost/content-data-admin/releases/20180814135728/config/environments/production …
```
> Remove logstasher from production.rb

- spec/temp_spec.rb
Temp spec was added to ensure that the application was working as
expected. This change will remove the spec as it is no longer needed.
> Remove temporary spec

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_info-metric.scss
- app/views/components/_info-metric.html.erb
- app/views/components/docs/info-metric.yml
- app/views/development/index.html.erb
- spec/components/info_metric_spec.rb
This component displays a metric alongside supporting information
with optional trend info and about text
https://trello.com/c/2ZuLZwCO/609-3-build-info-metric-component
> Add info-metric component

- app/controllers/metrics_controller.rb
- app/helpers/charts_helper.rb
- app/presenters/chart_presenter.rb
- app/services/metrics_service.rb
- app/views/metrics/show.html.erb
- config/routes.rb
- lib/gds_api/content_data_api.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/support/content_data_api.rb
To reduce the number of requests for fetching multiple metrics,
we are sending metrics as a single query parameter with multiple
values.
This change is reflected in the Content Data API
(content-performance-manager) as well[0].
We also add a gds-api-adapter stub to be more closely
aligned to the way the code would be structured in the gem, allowing
code that does not belong in the MetricsService to be abstracted
into GdsApi:ContentDataApi.
[0] https://github.com/alphagov/content-performance-manager/pull/872
> Multi chart endpoint

- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
We have changed the format of the payload returned from
the backend service. The old format was:
{
"unique_pageviews": {
"total": 100,
"latest": 50
}
}
The new format is:
{
"unique_pageviews": 100
}
This is part of Trello: https://trello.com/c/hjj6IJXH/621-3-show-metadata-information-in-the-single-performance-page-epic-2
> Refactor single content page for new data format

- app/presenters/chart_presenter.rb
- app/views/metrics/show.html.erb
Currently the app raises an error when no
time series data is returned from the back-end.
This commit checks foe empty series before
attempting to render the chart.
Trello: https://trello.com/c/hjj6IJXH/621-3-show-metadata-information-in-the-single-performance-page-epic-2
> Fix error when the backend has no data

- app/assets/stylesheets/components/_glance-metric.scss
- app/views/components/_glance-metric.html.erb
- app/views/components/_info-metric.html.erb
- spec/components/glance_metric_spec.rb
- switches the symbol used when there is no change in metric
- removes a border at mobile size
- removes link from glance metric, along with associated test
https://trello.com/c/xWh1yAwa/603-3-build-glance-metrics-component
> Update components to match latest design

- app/controllers/metrics_controller.rb
- app/helpers/charts_helper.rb
- app/presenters/chart_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/services/metrics_service.rb
- app/views/layouts/application.html.erb
- app/views/metrics/_metadata_row.html.erb
- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
This commit renders the metadata as shown in the [prototype](https://trello.com/c/tYOxhCi5/645-single-page-design-latest-updates) on the single content item page.
There is a [related pr in content-performance-manager](https://github.com/alphagov/content-performance-manager/pull/902)
Trello:  https://trello.com/c/hjj6IJXH/621-3-show-metadata-information-in-the-single-performance-page-epic-2
> Show content metadata on the single item page

- app/controllers/metrics_controller.rb
- spec/features/single_content_item_spec.rb
- spec/support/content_data_api.rb
Currently the app fails with a 500 error
when we get a 404 from the content-data-api.
This commit traps the error and renders the 404 page.
> Handle a GdsApi::HTTPNotFound when getting data

- app/controllers/metrics_controller.rb
- app/helpers/charts_helper.rb
- app/presenters/chart_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/services/metrics_service.rb
- app/views/layouts/application.html.erb
- app/views/metrics/_chart.html.erb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/support/metrics_chart_spec_helpers.rb
Add metric summary/chart for 
* number_of_internal_searches
* satisfaction_score
Also removed the unnecessary `metrics` parameter from the route as we don't need to configure which metrics we are showing and having to specify them is making it really annoying to test.
> Render the remaining metrics summaries/charts

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_metadata.scss
- app/views/components/_metadata.html.erb
- app/views/components/docs/metadata.yml
- app/views/development/index.html.erb
- spec/components/metadata_spec.rb
This adds the component for metadata. It expects the named parameters and whatever string is passed as each. Only status is optional. An example is included on the dev page:
http://http://content-data-admin.dev.gov.uk/dev
The docs are on the component guide page:
http://content-data-admin.dev.gov.uk/component-guide/metadata
Screenshot:
Trello: https://trello.com/c/jx0D5HKF/670-2-implement-metadata-component
> Add metadata component

- app/presenters/single_content_item_presenter.rb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
This commit shows the data in the components we have so far.
The components we are now using:
* components/metadata
* components/info-metric
* components/chart
Stuff in green - real data
Stuff in red - placeholders
Url: http://content-data-admin.dev.gov.uk/metrics/check-mot-history?from=2018-01-01&to=2018-10-01
> Hook up components

- Gemfile
- Gemfile.lock
- app/controllers/metrics_controller.rb
- app/models/date_range.rb
- app/presenters/chart_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/services/metrics_service.rb
- app/views/metrics/show.html.erb
- spec/factories/date_range.rb
- spec/features/date_selection_spec.rb
- spec/features/single_content_item_spec.rb
- spec/models/date_range_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/rails_helper.rb
- spec/support/content_data_api.rb
Add date range picker to single content item page in order to let end users get metrics for the time period in which they are interested in. Use `last 30 days` as default time period if none is specified.
No styling on the radio buttons as a component will be coming in the future which handles this.
Change the id's of charts and tables to make them easier to query. The date is not an important part of the chart because there will only be one per query and if we display two different time series on the same chart it could be difficult to handle.
> Add date range picker

- app/controllers/content_controller.rb
- app/presenters/chart_presenter.rb
- app/presenters/content_items_presenter.rb
- app/presenters/content_row_presenter.rb
- app/services/metrics_service.rb
- app/views/content/_content_row.html.erb
- app/views/content/index.html.erb
- config/routes.rb
- lib/gds_api/content_data_api.rb
- spec/features/date_selection_spec.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/support/content_data_api.rb
- spec/support/table_data_spec_helpers.rb
We now have a route that displays content items.
Example Url:
/content?date_range=last-30-days&organisation=6667cce2-e809-4e21-ae09-cb0bdc1ddda
This is not complete, This is an interim PR to allow the other stories on the index page 
to be played.
There is a [Related PR iin content-performance-manager](https://github.com/alphagov/content-performance-manager/pull/919)
> Add outline of index page at /content

- app/services/metrics_common.rb
- spec/features/date_selection_spec.rb
- spec/features/single_content_item_spec.rb
here is a problem with content-data-api that
causes a 500 error when there are nils in the
satisfaction_score column.
This PR temporarily removes this metric from the
call to content-data-api
> Disable satifaction score

- app/services/metrics_common.rb
We are currently experiencing performance problems
when retrieving data for the index page.
This commit (temporarily) increases the timeout
so we can render the page and development on it
can continue.
We will reduce the timeout again once the
query has been optimised in the content-data-api.
> Increase the timeout for GdsApi::ContentDataApi

- app/helpers/metrics_formatter_helper.rb
- app/presenters/chart_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/views/components/_info-metric.html.erb
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
The percentage figures for metrics are not presented as percentages but as whole numbers on the single page view.
This PR fixes that.
https://trello.com/c/DhJHJL6b/679-1-fix-formatting-of-numbers-percentages-for-single-page
> Fix format of percentage numbers

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_time-select.scss
- app/views/components/_chart.html.erb
- app/views/components/_time-select.html.erb
- app/views/components/docs/time-select.yml
- app/views/metrics/show.html.erb
- spec/components/time_select_spec.rb
- spec/features/date_selection_spec.rb
This adds the component that allows users to select the timeframe for the data they are viewing.
It also updates the view to use the component, and updates related tests.
This can be seen at 
http://content-data-admin.dev.gov.uk/component-guide/time-select
or single content item pages such as
http://content-data-admin.dev.gov.uk/metrics/government/publications/self-assessment-tax-return-sa100?utf8=%E2%9C%93&date_range=last-2-years
(note that this branch has inherited the satisfaction score bug from master, so you'll need to work around that to view it - remove the satisfaction graph in the view and line 4 of app/services/metrics_service.rb)
> Add time select component

- app/helpers/metrics_formatter_helper.rb
- spec/helpers/metrics_formatter_helper_spec.rb
When satisfaction score is not recieved due to existing problems with that metric
then currently we have an error raised in the format_metric_value method.
This PR ensures that this error will not be raised and that our app can handle nil
values for metrics which are measured as percentages.
> Fix bug metrics formatting bug

- app/presenters/chart_presenter.rb
- app/presenters/content_row_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/services/metrics_common.rb
- app/views/metrics/show.html.erb
- spec/features/date_selection_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
Requests now support the feedex_comments metric to display the aggregated and time series data for number of feedback comments. Graph and metric info components added to single page view for feedback comments.
> Add feedback comments metric to single page view

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_related-actions.scss
- app/views/components/_related-actions.html.erb
- app/views/components/docs/related-actions.yml
- app/views/layouts/application.html.erb
- app/views/metrics/_metadata_row.html.erb
- app/views/metrics/show.html.erb
- spec/components/related_actions_spec.rb
- spec/features/single_content_item_spec.rb
This included direct styling on the page, and adding an extra "related actions" component.
No screenshot as it would be the entire page, and should hopefully match the whole design for this page.
Example url: http://content-data-admin.dev.gov.uk/metrics/government/publications/self-assessment-tax-return-sa100?utf8=%E2%9C%93&date_range=last-6-months#number_of_internal_searches_chart
https://trello.com/c/u77qQMjx/674-build-view-for-single-content-item-page
> Style and lay out single content item page to match design

- app/services/find_content.rb
- lib/gds_api/content_data_api.rb
- spec/features/index_page_spec.rb
- spec/support/content_data_api.rb
This is a continuation of https://github.com/alphagov/content-performance-manager/pull/921.
The API has changed so we also need to update the way we pass the organisation
because it has been renamed from `organisation` to `organisation_id`
> Rename parameter: organisation to organisation_id

- doc/arch/adr-000-document-architectural-decisions.md
- doc/arch/adr-001-editing-microcopy.md
An rationale for why we are using Rails Internationalisation translations to power the microcopy in the app's interface.
> Adr editing microcopy

- app/controllers/metrics_controller.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/061BqCh7/688-1-display-the-application-that-published-the-page)
**As a** Content Designer
**I want** to know what application has created the document
**So** that I can edit it with the right application
Use the field `publishing_app` to display the application that edited 
the document. 
In future stories we will provide a link to open the document directly
in the publishing-app, but to keep the story simple, we will just render
the name of the application.
Adding a link to the publishing app depends on the specific format
of each application, so we would rather take this approach in smaller
steps and prioritise this work accordingly.
> Show publishing app in metadata section for the Single Performance Page

- lib/gds_api/content_data_api.rb
- spec/support/content_data_api.rb
`/content` is no longer part of our public API as it is only intended
for exploration in beta testing. 
This will prevent us from updating a documentation that is not currently
in used.
In incoming PRs we will:
Use a single endpoint to retrieve series and aggregations; this will allow us
to extract other endpoints out of our public API.
> Update `/content` endpoint: no longe lives within `/api`

- app/presenters/single_content_item_presenter.rb
- app/services/metrics_common.rb
- app/views/metrics/show.html.erb
- spec/features/date_selection_spec.rb
- spec/features/single_content_item_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/tYOxhCi5/645-single-page-design-latest-updates)
As a Content Designer
I want to know how many PDFs a content item has and how long it is
So that I can make the content item more accessible and readable
What
Add `number of pdfs` and `word count` metrics to single content item page.
Why
To illustrate the number of closed format attachments a single content item has
and the length of the content.
After:
> Add additional metrics to single content item page

- app/controllers/metrics_controller.rb
- app/models/date_range.rb
- app/presenters/glance_metric_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/_glance_metric.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- config/locales/views/metrics/en.yml
- spec/factories/date_range.rb
- spec/features/date_selection_spec.rb
- spec/models/date_range_spec.rb
- spec/presenters/glance_metric_presenter_spec.rb
This adds a glance metric presenter that helps combine metrics and text for locales to produce formatted text for use in views. This refactor allows better use of partials to reduce repetative code in the `metrics/show` view.
> Add glance metric presenter

- app/views/components/_chart.html.erb
- config/locales/views/components/en.yml
The dropdown text for the table tab is rendered using locales.
> Use locales for table tabs

- app/helpers/metrics_formatter_helper.rb
- app/services/metrics_common.rb
- spec/features/date_selection_spec.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
Also fix the formatting of percentage figures. The API already
calculates what the percentage figure should be, so we don't need to
multiply by 100 any longer. Also the design shows the percentages as
whole figures, as in 90% not 90.123%, so have tweaked that output to
match.
> Enable displaying of satisfaction score

- app/assets/stylesheets/components/_related-actions.scss
- app/views/components/_related-actions.html.erb
- app/views/metrics/show.html.erb
- config/locales/views/metrics/en.yml
- spec/components/related_actions_spec.rb
Remove the word `visit` from the link to content item on gov.uk link on
the single content item page.
The word `visit` is necessary for accessibility purposes but not helpful for
the design so this PR hides it using the visually-hidden class to allow
screen readers to understand it.
Before: 
After:
> Change link text as per designs

- app/presenters/single_content_item_presenter.rb
- spec/presenters/single_content_item_presenter_spec.rb
[Trello card](https://trello.com/c/061BqCh7/688-1-display-the-application-that-published-the-page)
Fixes the issue when displaying the name of the rendering app. We 
were showing `Travel-advice` when processing `travel-advice`, because
we were not removing the `-`
> Remove `-` when displaying publishing application

- app/helpers/metrics_formatter_helper.rb
- app/presenters/single_content_item_presenter.rb
- app/views/components/_chart.html.erb
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/support/content_data_api.rb
The charts were displaying odd v-axis values, and the figures for the charts for satisfaction score was also wrong.
> Fix charts for decimal vals and percentages

- app/helpers/metrics_formatter_helper.rb
- app/presenters/chart_presenter.rb
- app/presenters/content_row_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/views/components/docs/chart.yml
- app/views/content/_content_row.html.erb
- app/views/development/index.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/components/chart_spec.rb
- spec/features/date_selection_spec.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/content_row_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
It renames the metric names to mimic previous [work in Content Performance Manager][1]
This work raises some alarms because we shouldn't have to change that 
many names after a change in the API. 
I have not added a layer in between to map names because:
1. I would rather use exactly the same names for the time being
2. I think it is better to first clean up the codebase for the frontend and backend before making other design decisions.
[1]: https://github.com/alphagov/content-performance-manager/pull/945/files
> Rename attributes in content data admin

- app/helpers/metrics_formatter_helper.rb
- app/presenters/chart_presenter.rb
- app/presenters/single_content_item_presenter.rb
- lib/gds_api/content_data_api.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Merge after https://github.com/alphagov/content-data-admin/pull/111
Only commit to review:  8976c5a
In our codebase / tests we are not being consistent in using symbols
or string in hashes. Sometimes we even change the code to accommodate
symbols in our Fixtures.
This is not a very good practice, so I have symbolised the response
in origin (right after it is returned by the Adaptor) so that we can
be consistent in our codebase using symbols.
> Use symbolized response hash

- app/controllers/content_controller.rb
There is no need to symbolize a Hash because of https://github.com/alphagov/content-data-admin/pull/112
> Remove hash conversion so symbols

- app/presenters/glance_metric_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/_glance_metric.html.erb
- spec/features/single_content_item_spec.rb
- spec/presenters/glance_metric_presenter_spec.rb
Calculates the on page search rate. This is used in _'X% of users searched on this page'_. (See screenshot).
To give users some context around the search statistics to help them understand the relevance.
I considered making changes to the way we handle `@context_metrics` within `GlanceMetricPresenter.rb`.
I'm not sure that `@context_metrics` needs to be a hash, maybe we can simply render `@context_metrics` as a string depending on what the metric name is. In the future I think this will avoid running multiple unnecessary methods.
If the rest of the team thinks this is a good idea then I will address this in a separate PR.
> Add on page search rate

- app/views/layouts/application.html.erb
This PR adds the Google Tag Manager component and it needs [Add Google Tag Manager env vars for Content Data Admin](https://github.com/alphagov/govuk-puppet/pull/8193) to get merged in order to render the component. Raised this PR to have it ready.
Trello card (https://trello.com/c/ldax4jWq/631-1-embed-google-tag-manager-code-in-header-and-body-of-each-page-of-the-content-data-app#)
> Add google tag manager component to head of application layout

- app/controllers/metrics_controller.rb
- app/helpers/metrics_formatter_helper.rb
- app/presenters/chart_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/services/fetch_single_page.rb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- lib/gds_api/content_data_api.rb
- spec/features/date_selection_spec.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
Updating the single page presenter to use the new `/single_page` endpoint from content performance manager. Removed old request test stubs for access in the previous endpoints.
> Use single endpoint

- app/controllers/content_controller.rb
- app/services/fetch_organisations.rb
- app/views/content/index.html.erb
- lib/gds_api/content_data_api.rb
- spec/features/index_page_spec.rb
- spec/support/content_data_api.rb
A dropdown to display all the organisations and allow the user to choose to filter content by chosen organisation i.e to only display content that belongs to the selected organisation.
[Trello card](https://trello.com/c/nQxldbA2/661-1-index-page-filter-by-organisation#)
To allow the user to filter down to the content that is most important to them.
The dropdown menu is not the final design, this PR sets up the logic and in future we will use a govuk component for the dropdown.
> Add dropdown menu to filter by organisation

- app/presenters/single_content_item_presenter.rb
- app/views/components/_info-metric.html.erb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
Previous commits added the figure to the glance metrics. This commit uses the recent refactor to enable the the number to be output within the metric header section.
Screenshots from a branch deploy on integration:
> Add number of responses for satisfaction score

- app/views/components/_time-select.html.erb
- app/views/metrics/show.html.erb
- spec/components/time_select_spec.rb
https://trello.com/c/MC1QwkUL/738-3-index-page-update-date-select-component-so-it-becomes-part-of-another-form
We want to use this form section within the form on the index page, since it was a standalone form originally this wouldn't have been possible so in this PR we move the form tags into the view template leaving the component as a form partial. In the original view the component also rendered the submit button and because it is hidden in the reveal, I have had to preserve that ability. Since we don't want it on the index page, though, it is now parameterised. Visually there are no changes.
> Update time select component to allow it to be embedded in another form.

- app/controllers/content_controller.rb
- spec/features/index_page_spec.rb
[Trello card](https://trello.com/c/nQxldbA2/661-1-index-page-filter-by-organisation)
Currently after filtering if the user clicks on a content item title the page will
not load due to an empty date range param. This bug was discovered after we added
the filter by organisation functionality.
This PR allows for empty date range params and persists any existing date range params
i.e if in the future we filter the index page to show data from the last 2 years then the page data
page will reflect this.
> Allow organisation filtering to respect date range

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_chart.scss
- app/assets/stylesheets/components/_glance-metric.scss
- app/assets/stylesheets/components/_info-metric.scss
- app/assets/stylesheets/components/_metadata.scss
- app/assets/stylesheets/components/_related-actions.scss
- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/metrics/_show.scss
- app/views/components/_chart.html.erb
- app/views/components/_glance-metric.html.erb
- app/views/components/_info-metric.html.erb
- app/views/components/_metadata.html.erb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- package.json
- spec/components/metadata_spec.rb
- spec/features/single_content_item_spec.rb
https://trello.com/c/csZsWZNy/736-3-page-data-make-layout-work-at-mobile-and-tablet-breakpoints
Matching styles against designs for desktop and mobile:
https://drive.google.com/open?id=194icCuUprUsYYtakbUHGZbDQySoLnCSe
https://drive.google.com/open?id=1IHYvkjQm_ZAU9Er-cIdAapNLZ7qEDOns
Some changes to CSS classes, building on top of recent changes in the gem.
> Add styling for mobile views, tweak desktop view to match design.

- app/views/layouts/application.html.erb
https://trello.com/c/8DZgZKZn/739-3-add-banner-beta-state-feedback-app-name
Adds the phase (beta) banner, and updates the name in the main banner. Link location is yet to be decided so is currently blank.
> Add phase banner and update app name

- config/environments/development.rb
Changed file checker to use polling rather than system events to allow automatic code reload within the development environment in the VM. This is due to system events not being passed to the VM.
> Use rails polling file checker

- app/views/components/_info-metric.html.erb
We want to add links into the About bits of microcopy. We need to
disable the HTML escaping for the links to work.
> Enable links in translations

- app/presenters/single_content_item_presenter.rb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Adding a link to the feedback explorer in the feedback comments section. 
Note: the spacing is wider than the design due to complexity issues of custom spacing. This was agreed as and should be revisted in a future PR.
> Feedback explorer link

- config/locales/views/components/en.yml
Removed 'View' from the beginning of the table reveal description to reflect the design.
> Rename table reveal

- app/presenters/single_content_item_presenter.rb
Removed the use of Addressable when generating the feedback link as this is developer dependency and not avaiable in the production environment.
> Remove developer dependencies for feedback link

- app/presenters/single_content_item_presenter.rb
- spec/features/single_content_item_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/TdGevWTq/764-1-page-data-fix-of-users-searched-the-page-in-the-at-a-glance-metrics)
This PR is to fix a bug (see trello card) which has crept into the code base resulting in `search_rate` for a content item being calculated incorrectly.
Search rates were being calculated incorrectly due to our use of the method
`number_with_delimiter` which, for example, returns '10,000' when passed 10000.
Calling `to_f` on '10,000' returns 10 and this is the cause of our current incorrect
calculation for search_rate on some pages.
This is solved by formatting the `total_searches` and `total_pviews` into
a float before using them to calculate `on_page_search_rate`.
This PR adds a test for this functionality and makes changes to default data in order
to test that this bug …
> Fix search rate bug

- app/controllers/content_controller.rb
- app/services/fetch_document_types.rb
- app/services/find_content.rb
- app/views/content/index.html.erb
- lib/gds_api/content_data_api.rb
- spec/features/index_page_spec.rb
- spec/support/content_data_api.rb
This commit allows filtering by document_type:
It is dependant on [This PR in content-performance-manager](https://github.com/alphagov/content-performance-manager/pull/964)
Url to test : http://content-data-admin.dev.gov.uk/content?utf8=%E2%9C%93&organisation_id=b8a6a8f2-d04f-4346-90c1-d28898565866&document_type=corporate_report&date_range=last-30-days&commit=Filter
> Allow filtering by document type

- app/presenters/single_content_item_presenter.rb
As suggested in [this comment](https://github.com/alphagov/content-data-admin/pull/151/files#r227791900)
Use metric values to stop us from needing to format the human readable
version of them before using for calculations.
> Refactor on_page_search_rate

- app/views/layouts/application.html.erb
In creating the reference index page I removed this call to the js as the gem appears to call it in for us in the admin layout already. However I have now realised that the call needs to be in the head of the page for our charts to work. This will need to be resolved properly later but so I don't leave the charts broken in my absence this is a quick patch. I'm creating a separate ticket in trello to address this fully and to scope the js properly.
> Fix js issues

- app/presenters/single_content_item_presenter.rb
- app/views/components/_info-metric.html.erb
- app/views/metrics/_metric_header.html.erb
- config/locales/views/components/en.yml
- spec/features/single_content_item_spec.rb
This enables the use of the short metric title in the about label within the locales.
> Add metric name in about metric label

- app/presenters/single_content_item_presenter.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/TdGevWTq/764-1-page-data-fix-of-users-searched-the-page-in-the-at-a-glance-metrics)
We currently use pageviews to calculate search rate, this PR changes it so that
we will use unique pageviews.
Some changes to the test data.
Unique pageviews more accurately represents the idea of 'How many users searched per page'.
Changing the test data was necessary to make it closer to the kind of data that we will see in production.
---
> Use unique pageviews for search rate

- app/views/content/_content_row.html.erb
- app/views/content/_page_title.html.erb
- app/views/content/index.html.erb
- spec/features/index_page_spec.rb
Publishing Workflow have built a table component in the gem, we need to implement this. Later we can expand upon it to meet our designs. 
Reuse of code, prevents duplication of effort, gives a good starting point for making our tables match the designs.
---
> Use table component on index page

- app/views/components/_chart.html.erb
https://trello.com/c/drqNn996/774-1-hide-legend-on-chart
Remove the legend from the chart
To match design - context is clear from headings so legend is unnecessary
---
> Remove legend from charts

- app/assets/stylesheets/components/_chart.scss
- app/views/components/_chart.html.erb
Apply the scroll to the table and not the table header
https://trello.com/c/0uFwHlct/782-1-about-this-data-detail-link-disappears-when-user-scrolls-horizontally
So that users can access the show/hide mechanism after scrolling without having to scroll back
> Fix table scroll

- app/controllers/content_controller.rb
- spec/features/index_page_spec.rb
By default, pre-populate filters and data with the user's organisation.
The most common scenario is for users to search/edit content for their organisation.
---
> Use users organisation on index page

- app/views/components/_chart.html.erb
Add a vertical crosshair to charts on hover and select
https://trello.com/c/dHyNZPLB/784-2-add-vertical-crosshair-to-charts
Match the designs better, allow user to see link to horizontal axis
> Add vertical crosshair to charts

- app/presenters/single_content_item_presenter.rb
- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/174c4iAe/758-2-page-data-add-pageviews-per-visit-metric)
Add pageviews per visit metric to single content item page
So that users can measure how many times the page is viewed by an individual user in order to judge the performance of the page.
---
> Add pageviews_per_visit metric

- app/views/components/_chart.html.erb
We previously removed the legend config and lost the legend we intended
to remove from the top of the chart. It had the unexpected effect of
creating a legend label at another position where it didn't fit. This
specifically removes it fully.
https://trello.com/c/s8pyUWgc/785-bug-fix-line-appearing-to-the-right-of-all-charts
> Remove default legend

- app/presenters/single_content_item_presenter.rb
- spec/presenters/single_content_item_presenter_spec.rb
We currently have a bug which raises an error when calculating searches per page
if we do not have any data for either pviews or upviews for a certain period. It was introduced in [this PR](https://github.com/alphagov/content-data-admin/pull/159)
This bug has raised it's head when we set the date range to a period longer than we
have data for. This is because we will not have any data for the previous period, which
we use to calculate trends and so we get the error which is raised by this bug:
'`NoMethodError: undefined method `zero?' for nil:NilClass'
This PR calls `.to_f` on the value field of pviews and upviews. This will convert nil to 0
which will stop the error being raised if we receive a nil value.
If we do not have any value for a set period then we will set pageviews per visit …
> Fix searches_per_visit_bug

- app/presenters/single_content_item_presenter.rb
- config/locales/views/components/en.yml
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
Displaying whether a content item Withdraw or in History Mode or both.
To allow users to see the status of a piece of content.
---
> Add withdrawn and history mode status

- Gemfile
- Gemfile.lock
- app/controllers/content_controller.rb
- app/helpers/pagination_helper.rb
- app/presenters/content_items_presenter.rb
- app/services/find_content.rb
- app/views/content/index.html.erb
- lib/gds_api/content_data_api.rb
- spec/features/index_page_spec.rb
- spec/helpers/pagination_helper_spec.rb
- spec/presenters/content_items_presenter_spec.rb
- spec/support/content_data_api.rb
Add pagination to the index page
So the user can view more than the first page.
There is a related [PR in content-performance-manager](https://github.com/alphagov/content-performance-manager/pull/974)
Url to test: http://localhost:3230/content?date_range=last-month&document_type=&organisation_id=c36bd301-d0c5-4492-86ad-ee7843b8383b&page=4
> Pagination

- app/views/components/_chart.html.erb
- spec/features/single_content_item_spec.rb
The values should use a delimiter for large numbers to be more readable.
This change formats the numbers to use locale based format delimiters.
Number in tables do not display with delimiter. 
---
> Add formatting to table values

- spec/features/single_content_item_spec.rb
I must have rebased badly in the past.
There was a spec disabled among the feature tests. It seems to have been from a WIP commit.
We should enable and fix our feature tests to ensure good coverage.
> Re-enable test

- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
Remove placeholder text in glance metrics for Unique Pageviews.
Figures for percentage of value against the whole of an organisation's
is descoped for private beta.
---
> Remove placeholder text for unique pageviews

- app/views/metrics/_metric_section.html.erb
Remove the placeholder Download links for each metric on the single page performance page.
Deprioritising for private beta, as we are no longer sure this feature
is appropriate.
---
> Remove placeholder download links on single page

- config/locales/defaults/en.yml
Change 'Google Analytic' to 'Google Analytics' so there isn't a typo when we release private beta.
> Fix typo in 'About pageviews per visit'

- Gemfile
- Gemfile.lock
- bin/rails
- bin/rake
- bin/rspec
- bin/spring
I had wrongly assumed in 63971e15c316e941287079ad06147d9660fa2458 that
this allowed me to just run rspec. Since upgrading local ruby version
I've realised I must have installed rspec globally. This also adds other
binstubs for running rake and rails commands via spring.
Note: I also have a this local alias:
`alias rspec=./bin/rspec`
> Add spring-commands-rspec gem

- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/content/_index.scss
- app/controllers/content_controller.rb
- app/views/content/index.html.erb
https://trello.com/c/QnkuOdxM/825-3-build-index-page-to-match-designs-including-mobile-views
This brings the index page more in line with the designs, including:
- Adjusting the page to go full browser width
- Putting a fixed width on the table to avoid wrapping (will be iterated on in future as it currently breaks outside page width and is a bit weird, but works)
- Changing font sizes and adjusting padding
- Labelling numeric cells so they gain right-alignment
> Update index page to match design

- app/models/calculator/pageviews_per_visit.rb
- app/models/calculator/trend_percentage.rb
- app/presenters/single_content_item_presenter.rb
- app/views/components/_glance-metric.html.erb
- app/views/components/_info-metric.html.erb
- spec/components/glance_metric_spec.rb
- spec/components/info_metric_spec.rb
- spec/features/single_content_item_spec.rb
- spec/models/calculator/pageviews_per_visit_calculator.rb
- spec/models/calculator/trend_percentage_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/a34qyfIg/786-2-page-data-display-no-data-when-there-isnt-comparison-data-available-for-a-previous-time-period)
Display 'no comparison data' when we have no previous data with which to compare current data.
Currently we display a trend percentage of 0% if we have no previous data.
Displaying a 0% change for both an actual 0% change as well as an unknown change is incorrect and is likely to be confusing for end users who do not know which of the two scenarios that the 0% change would relate to.
---
> Handle no comparison data

- app/models/date_range.rb
- app/views/content/index.html.erb
- app/views/metrics/show.html.erb
- spec/features/date_selection_spec.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/models/date_range_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Change date ranges so that the range ends `yesterday` rather than `today`
We get data every day for the previous day's data. This means we never have `today`'s data. This has become an issue when comparing previous periods to the current period as we have one day less than is expected in the current period.
---
> Time periods start yesterday

- app/views/components/_metadata.html.erb
- spec/components/metadata_spec.rb
https://trello.com/c/eJtCoZ3g/826-page-data-fix-formatting-of-metadata-when-we-have-no-value-for-primary-publishing-organisation
Guards against empty metadata items and renders nothing for blank fields
Layout currently breaks when the value is empty
> Guard against missing data to avoid layout breaking

- app/presenters/single_content_item_presenter.rb
- spec/presenters/single_content_item_presenter_spec.rb
[Trello card](https://trello.com/c/a34qyfIg/786-3-page-data-display-no-data-when-there-isnt-comparison-data-available-for-a-previous-time-period#)
Fix trends in the at a glance section of the single page data page for the `past-month` date range.
At a glance trends currentl returns `no comparison data` when the
date period `last-month` is selected. This is because we checked for
complete data based on the number of days in each month being the
same. Obviously this is not the case.
This PR changes the logic for the `past-month` date range in order to
check that the previous month has data for each day in the month,
regardless of the length of the month and regardless of how many
days are in the current month.
---
> Fix last-month comparison data bug

- app/presenters/content_items_presenter.rb
- spec/presenters/content_items_presenter_spec.rb
Make 'All document types' the first option in select dropdown in the filter for the content page.
Typical position a user would look for the 'All documents types' option
---
> Fix position of 'All document types' in filter options

- app/presenters/content_row_presenter.rb
- spec/features/index_page_spec.rb
- spec/presenters/content_row_presenter_spec.rb
[Trello card](https://trello.com/c/FVwAMbMc/837-2-index-page-add-number-of-responses)
We were not showing the number of responses to user satisfaction surveys
in our UI. This PR allows us to show the number of responses.
The problem was caused by us referencing `satisfaction_responses` when
in the api response the correct key is `satisfaction_score_responses`.
This PR corrects this error and updates the tests to reflect this.
---
> Fix satisfaction responses bug

- Gemfile
- Gemfile.lock
Including the optional binding_of_caller dependency. This provides a
REPL on the error page, which is useful for debugging.
> Add the better_errors gem to the Gemfile

- app/views/layouts/application.html.erb
Add the organisation_slug for the current user to the dataLayer
So that it's picked up and recorded in Google Analytics. This is a
copy of the functionality in Content Publisher.
https://trello.com/c/dR47oQfR/828-2-page-data-and-index-page-add-the-user-account-organisation-to-the-gtm-data-layer
---
> Add the organisation_slug for the current user to the dataLayer

- app/presenters/chart_presenter.rb
- app/views/components/_chart.html.erb
- spec/components/chart_spec.rb
- spec/features/date_selection_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/chart_presenter_spec.rb
Display the full date range in the charts and tables, even when we have no data for all or some of that time period.
Currently, the date range displayed in the charts & tables matches dates that we have data for (and ignores dates we don't have data for).
It's misleading for users of Content Data app if the date range in the charts & tables doesn't match the date range they have selected.
This problem will regularly occur for newly published content.
---
> Show blank regions in charts and tables

- Gemfile
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/metrics/_show.scss
- app/views/layouts/application.html.erb
- app/views/metrics/show.html.erb
https://trello.com/c/7GmgyJiT/834-2-update-header-to-match-designs-and-content-publisher
Update the header area to match design
- change text for feedback link
- add search link in banner region
- remove "back" link
- make entire headers full width on index
> Allow full width header and add search link in banner region

- app/assets/images/question_mark_default.svg
- app/assets/stylesheets/content/_index.scss
- app/views/content/index.html.erb
https://trello.com/c/fOwe3KC3/840-2-index-page-add-help-text-to-headers-on-table
This is the initial implementation which puts an SVG on the page,
and gives it a title tag - this means text will appear on a prolonged hover.
This also adds styles to support the table when we put it into the
non-sortable mode and applies that mode.
Move closer to designs, allow users to see help text.
> Add help text to index page table

- app/views/content/index.html.erb
https://trello.com/c/4KBkjwCe/860-1-change-order-of-filters-on-index-page
Reorder and rename form fields to match the PW app.
> Re-order filters and update search label

- app/helpers/pagination_helper.rb
- app/presenters/content_items_presenter.rb
- app/presenters/pagination_presenter.rb
- app/views/content/_table_data_description.html.erb
- app/views/content/index.html.erb
- spec/presenters/content_items_presenter_spec.rb
- spec/presenters/pagination_presenter_spec.rb
Make the page information in the table header show real numbers
We currently only have placeholder text.
This only includes the page information. The filter information will be in another PR.
Trello: https://trello.com/c/BZrqyTPo/830-2-index-page-add-information-above-the-table-to-indicate-filters-applied
---
> Add page information above table

- app/views/content/index.html.erb
Change the 'clear filters' label to 'clear all filters' 
So Content Data app is consistent with Content Publisher and we state explicitly what happens.
---
> Rename 'clear filters' label

- app/controllers/concerns/exportable_to_csv.rb
- app/controllers/content_controller.rb
- app/presenters/content_items_csv_presenter.rb
- app/presenters/content_items_presenter.rb
- app/services/find_content.rb
- app/views/content/index.html.erb
- lib/gds_api/content_data_api.rb
- spec/features/index_page_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- spec/support/content_data_api.rb
Make it possible for a user to download data as a CSV from the index page. The CSV download should respect the filters that a user has applied (date, organisation, document type, title/URL)
We identified a need in user research for some of our users to download data from Content Data and do further analysis.
https://trello.com/c/yLoOoyUv/864-5-index-page-add-download-csv
---
> Add initial CSV export from the index page

- app/services/find_content.rb
- lib/gds_api/content_data_api.rb
- spec/features/index_filter_by_title_spec.rb
- spec/features/index_page_spec.rb
- spec/support/content_data_api.rb
Use date range to query warehouse content endpoint
We are using materialised views to render content from the content endpoint in our back end. The content end point is set up to use a `date_range` metric rather than `from` and `to` metrics. This makes sense as it will be much easier to identify the required view from a `date_range` param rather than having to do complex logic to determine the required view from `from` and `to` params.
This PR will not make any difference to the functionality of our index page on it's own. We currently have the back end hard coded to only ever show data from the last 30 days. It does however need to be merged before the back end changes so as not to break existing functionality.
---
> Use date range to query warehouse content endpoint

- app/presenters/chart_presenter.rb
- app/views/components/_chart.html.erb
- spec/presenters/chart_presenter_spec.rb
- prevent chart displaying negative numbers when all data is 0s
- prevent chart displaying fractional numbers in labels
- set sensible ranges on charts depending on max value in data, including capping charts showing percentages at 100
Improve y axis as per 
https://trello.com/c/gVCYMq4q/869-3-improve-vertical-axis-on-charts
More logical chart views
> Improve y-axis on charts

- config/locales/views/metrics/en.yml
- spec/helpers/external_links_helper_spec.rb
Explain that changes are made in GOV.UK Support. 
Users don't all know what 'mainstream' means.
> Edit text for linking to support form

- app/views/components/_chart.html.erb
- spec/components/chart_spec.rb
Replace nils with 0 when calculating max value for chart.
We now allow nulls in the data.
The chart component is trying to find the max value for each
row in the dataset. If any of these are nil, the .max call fails.
---
> Fix crash on single item page.

- app/controllers/content_controller.rb
- app/controllers/metrics_controller.rb
- app/models/date_range.rb
- app/views/content/index.html.erb
- app/views/metrics/show.html.erb
- config/locales/views/metrics/en.yml
- spec/factories/date_range.rb
- spec/features/date_selection_spec.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/models/date_range_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
The date-range parameters have been renamed as follows:
last-30-days => past-30-days
last-3-months => past-3-months
last-6-months => past-6-months
last-year => past-year
To be consistent with the text in the UI
---
> Change date-range parameters to match front-end

- app/presenters/content_items_presenter.rb
- app/presenters/filter_presenter.rb
- app/views/content/_table_data_description.html.erb
- app/views/content/index.html.erb
- spec/features/index_page_spec.rb
- spec/presenters/content_items_presenter_spec.rb
- spec/presenters/filter_presenter_spec.rb
- spec/support/content_data_api.rb
Add the text above the table to indicate what filters are applied. This should change when a user changes the filters applied.
Currently, we only have placeholder text for UKVI. We need to implement this functionality for private beta.
https://trello.com/c/BZrqyTPo/830-2-index-page-add-information-above-the-table-to-indicate-filters-applied
---
> Add filter information above table

- config/locales/views/metrics/en.yml
This PR changes the formatting of the browser title from "Page data: <content_title>" to "<content_title>: Page data"
To allow user to differentiate tabs based on which content item they represent.
---
> Change browser title

- app/views/components/_metadata.html.erb
- spec/components/metadata_spec.rb
- spec/features/single_content_item_spec.rb
#What
Don't display 'published' and 'last updated' in metadata on the Page Data page.
#Why
We don't trust dates to be accurate and are worried we'll mislead our users. We need to investigate the accuracy of dates more thoroughly before we can display them to users.
---
> Remove `Published` and `Last updated`

- app/helpers/external_links_helper.rb
- app/presenters/single_content_item_presenter.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/external_links_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/ayMhg8gT/877-3-add-links-to-the-correct-publishing-application-or-support-route-part-2#)
This PR adds links to edit the content in additional publisher applications. Namely:
- Contacts
- Specialist Publisher
- Travel Advice Publisher
For `collections` we link to the 'Content change request' support form as noted on the trello card.
Previously we did not show any links for documents published from these publishing applications.
---
> Add links to content items publisher application

- app/controllers/concerns/exportable_to_csv.rb
- app/controllers/content_controller.rb
- app/presenters/content_items_csv_presenter.rb
- spec/presenters/content_items_csv_presenter_spec.rb
https://trello.com/c/yLoOoyUv/864-5-index-page-add-download-csv
This generates filenames like `content-data-export-from-2018-10-26-to-2018-11-25-from-government-digital-service.csv`, rather than the previous `download.csv`.
> Use better filename for CSV download

- app/views/components/_chart.html.erb
- app/views/layouts/application.html.erb
`application.js` is linked twice, in `layout/application.html.erb` and also as part of the layout_for_admin GOV.UK publishing component.
https://github.com/alphagov/govuk_publishing_components/blob/81d7aaf/app/views/govuk_publishing_components/components/_layout_for_admin.html.erb#L21
> Remove duplicate linking of application.js

- app/presenters/content_row_presenter.rb
- app/views/content/_page_title.html.erb
- spec/presenters/content_row_presenter_spec.rb
Add a data attribute link to make Google Tag Manager tracking easier.
Currently the only way of tracking content type is by using custom javascript.
---
> Add data attribute for link

- app/presenters/filter_presenter.rb
- spec/features/index_page_spec.rb
- spec/presenters/filter_presenter_spec.rb
Allow filtering by `All organisations` and `No primary organisation`
Some content doesn't have a primary organisation. In our current implementation content without a primary organisation is not findable. Adding a no organisation option to the filter will make it possible to find all content. It will also help us surface the size of the content estate with no primary organisation.
Some of our GDS users care about all organisations content.  We think there is a need for some to see the highest traffic content on GOV.UK, irrespective of department
This PR is based in the fix in [PR 248](https://github.com/alphagov/content-data-admin/pull/248). So that should get merged first.
---
> Add all orgs and no orgs to filter

- app/presenters/filter_presenter.rb
- app/presenters/pagination_presenter.rb
- app/views/content/_table_data_description.html.erb
- spec/features/index_page_spec.rb
- spec/presenters/pagination_presenter_spec.rb
This adds the title or slug search terms to the filter description, removes full stop at end of description and formats the numbers using delimiters.
This helps user see what filters are currently applied. 
---
> Add title/slug search terms to filter description

- app/presenters/filter_presenter.rb
- app/views/metrics/show.html.erb
- config/initializers/inflections.rb
- spec/presenters/filter_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/xMSR3zFQ/899-3-change-document-types-to-the-correct-case-in-the-filter-list-and-in-the-metadata-section)
Format document types so that some acronyms are properly capitalised.
In order to help end users more easily understand the document types.
> Format document types

- config/routes.rb
- spec/features/index_page_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- spec/routing/single_page_routing_spec.rb
Add a route to handle the GOV.UK homepage
The current routing fails because the base_path to the GOV.UK homepage
is an empty string once you have removed the leading `/`
Trello https://trello.com/c/q9YG0Ftm/915-fix-bug-with-rendering-the-govuk-homepage-in-content-data-admin
there is a [related PR in content-performance-manager](https://github.com/alphagov/content-performance-manager/pull/1033)
Only after is shown. 
!!!BOOM!!! 500 Error
---
> Add route to handle homepage on single item page

- app/views/content/_table_data_description.html.erb
- config/locales/defaults/en.yml
- spec/features/index_page_spec.rb
- spec/support/content_data_api.rb
Correct the pagination description when no matching results.
This was saying "1 to 0 of 0 results"
now its says "no matching results"
---
> Handle no items in the pagination description.

- app/views/layouts/application.html.erb
We want to ensure that all code deployed to production goes through the normal development process. This block list will prevent Google Tag Manager from running any custom code which may have not been code reviewed.
> Block Custom HTML, Javascript and Pixels from GTM

- app/models/date_range.rb
- app/views/content/index.html.erb
- app/views/metrics/show.html.erb
- spec/features/date_selection_spec.rb
- spec/features/single_content_item_spec.rb
- spec/models/date_range_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Most of the date ranges were off by 1 day being inclusive of the `to` and `from` dates specified.
To make the date ranges accurate to the time period specified and comparable to data sources i.e. Google Analytics
---
> Fix date ranges to be accurate

- config/locales/defaults/en.yml
About pageviews per visit
CHANGED
It shows on average how many times a page was viewed during users’ session.
TO
It shows on average how many times a page was viewed during a user's session.
WHY
It's grammatically incorrect
About user satisfaction score
CHANGED
For a more reliable score on a page that doens't have many responses, choose a longer time period.
TO
For a more reliable score on a page that doesn't have many responses, choose a longer time period.
WHY
Spelling mistake
> Fix typos in contextual help

- app/presenters/single_content_item_presenter.rb
- app/views/components/_metadata.html.erb
- app/views/components/docs/metadata.yml
- app/views/metrics/show.html.erb
- spec/components/metadata_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Remove the code that parses/formats published_at and last_updated
We have an error formatting published_at when it is null.
As we are no longer displaying the data, the code to parse/format
it is redundant. This commit removes it.
Url to test: http://content-data-admin.dev.gov.uk/metrics/guidance/the-highway-code/traffic-signs
If you can see the page - the bug is fixed.
Trelllo: https://trello.com/c/ozp8d9RM/929-2-placeholder-traffic-signs-content-not-loading 
---
> Remove references to date fields.

- app/controllers/content_controller.rb
- spec/features/index_page_spec.rb
Change the default filter to `All Organisations`
We have found from user research that users are having
problems finding content.
We think this is because of the organisation filter which defaults
to the users organisation.
---
> Change the default filter to `All Organisations`

- app/views/content/_table_data_description.html.erb
- spec/features/index_page_spec.rb
Fix the text in the table header
Previously the table header said:
`Showing Showing 1 to 2 of 2 results for...`
This commit removes the repeated word so now it says:
`Showing 1 to 2 of 2 results for...`
Trello: https://trello.com/c/cx3X7pIT/934-2-filter-description-says-3-results-instead-of-2-results
---
> Fix `Showing` appearing twice in the header

- app/services/find_content.rb
- spec/features/index_page_spec.rb
Beefed up the test and make the CSV download respect all the
filters.
The CSV download was ignoring the `title or URL` filter.
Test by filtering the index page, download a CSV, it should have the same rows.
---
> Make the CSV download respect the filter

- app/presenters/content_items_csv_presenter.rb
- spec/presenters/content_items_csv_presenter_spec.rb
Handle `No organisations` and `No organisation` filter
in CSV download.
CSV Download was failing when `All organisations` or
`No primary organisation` is selected.
This was because it was trying to get the organisation
name to generate the filename.
`all` and `none` do not exist in the list of organisations so this was
failing.
Short-circuit for `all` and `none` to return `All organisations` and
`No organisation`.
> Handle CSV filename for all/no orgs.

- app/presenters/pagination_presenter.rb
- app/views/content/_table_data_description.html.erb
- spec/features/index_page_spec.rb
- spec/presenters/pagination_presenter_spec.rb
- spec/support/content_data_api.rb
Format page numbers in the /content table header
We were showing numbers formatted with commas in the
pagination description above the table.
I seem to have removed it accidentally.
This commit corrects that and adds to the feature
test for the index page to make sure we can't break it again.
Now all page numbers are formatted, not just the total.
---
> Fix formatting of numbers in table header

- app/helpers/external_links_helper.rb
- app/presenters/single_content_item_presenter.rb
- spec/helpers/external_links_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
Links to edit `manual_sections` in Manuals Publisher require the
`content_id` of it's parent `manual`. This is now sent as
`parent_content_id` from the API.
---
> Fix link to Manuals Publisher for manual_section

- app/views/components/_chart.html.erb
Fix the truncation of long numbers on the chart Y axis
Without this fix long numbers are not legible
https://trello.com/c/anAJGHjl/1006-x-axis-values-over-100000-wrap-to-2-lines-on-the-performance-page
The fix works by checking the max value that we are already collecting, and if it is above the threshold where it wraps or is hidden then we reduce the width of the chart from 90% to 80%, giving the edge more space for the labels on the Y axis.
> Fix truncation of large numbers on chart

- app/views/content/_table_data_description.html.erb
- spec/features/index_page_spec.rb
Don't show `1 to 2 of 2 results` when there is only one page.
It's a bit naff
Trello: https://trello.com/c/I5JI3AH5/1020-showing-1-to-2-of-2-less-than-100-results
---
> Pagination when less than 100 results

- app/presenters/content_items_csv_presenter.rb
- spec/presenters/content_items_csv_presenter_spec.rb
Changing the format of the satisfaction score metric from decimal to percentage. I.e 0.50 -> 50%
Formatting is easier to read and natural as percentage.
---
> Change format of satisfaction score in Content CSV

- app/assets/stylesheets/components/_glance-metric.scss
- app/assets/stylesheets/components/_related-actions.scss
- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/metrics/_show.scss
- app/views/components/_info-metric.html.erb
Two updates in one as they're so tiny:
1) Fix the incorrect style on the credit text in the about section
https://trello.com/c/GHRzAsdh/1023-1-wrong-font-style-on-second-paragraph-in-about-this-metric-descriptions
2) Update borders and horizontal rules to all be 1px
https://trello.com/c/jkTO5LCm/1024-1-all-horizontal-rules-to-be-1px-thick
Meet design aspirations, standardise elements
> Frontend fixes

- app/assets/stylesheets/metrics/_show.scss
- app/views/metrics/show.html.erb
Bring the last section of the page in line with the margins for the rest
Buggy layout needs fixing
> Re-align quality metrics layout

- app/assets/stylesheets/components/_time-select.scss
- app/views/components/_time-select.html.erb
Reduce space after heading on time select
https://trello.com/c/knEyUjiU/1027-1-decrease-the-gap-between-the-heading-and-the-link-in-the-date-range-picker
Meet design requirements
> Close up space after heading on time select component

- config/routes.rb
Our frontend dev uses `/dev` for testing and development of components and styles as part of their development workflow but this route is live on production. This change sets it to 404 on any other environment but development and integration.
Users shouldn't be seeing this page.
---
> Restrict /dev route to development and integration environments

- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/content/_index.scss
Resize headings
https://trello.com/c/qHoeN2OC/1028-1-make-all-headings-in-the-filter-column-and-the-sentence-summary-font-size-16px
PR also adjusts spacing so the text in the left and right columns align properly.
Match designs, fit more on screen
> Reduce font size of headers on index page

- app/presenters/content_items_csv_presenter.rb
- app/presenters/filter_presenter.rb
- lib/gds_api/content_data_api.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/UON8CWKJ/1057-1-tidy-up-endpoints-to-list-organisations-and-document-types)
We will no longerrely on the endpoints: `/organisations` and `/content_types`. We will start using `/api/v1/document_types` and `/api/v1/organisations`.
> Use new endpoints for document types organisations

- app/assets/stylesheets/content/_index.scss
Resize fonts, make headings bold, make table cells with numbers use the correct font
https://trello.com/c/0wrQu0gW/1030-1-font-sizes-for-the-index-table-contents-and-column-headers-to-14px
https://trello.com/c/qHoeN2OC/1028-1-make-all-headings-in-the-filter-column-and-the-sentence-summary-font-size-16px-make-filter-names-bold
https://trello.com/c/CP2ty8Ap/1052-1-make-sure-that-the-cells-in-the-index-page-table-that-contain-numbers-are-using-the-nta-tabular-numbers-font
Match design, fit more onto screen
> Make filter headings bold and reduce font size on table

- config/locales/defaults/en.yml
Change the feedback comments short title to 'Number of feedback comments'.
#Why
User research shows that users expect 'About feedback comments' to contain the feedback comments. The change will help clarify that this is information about the metric rather than the comments.
I've checked the other places this is used (index page, at a glance metrics) and we have space for the longer title.
> Clarify feedback comments short title

- app/presenters/single_content_item_presenter.rb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
[Trello card](https://trello.com/c/sVHzYTTF/1058-1-capitalise-pdfs-in-about-number-of-pdfs-link)
The link should say 'About number of PDFs' for consistency with the 'Number of PDFs' heading.
It looks like there is code to make the whole of a metric's short title lower case when it follows 'About' (Polly can't change it in the YAML file). It's only the first letter that needs to be lower case ie 'About number of PDFs' rather than 'About number of pdfs'.
> Fix number of pdfs copy

- app/presenters/filter_presenter.rb
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
- spec/presenters/filter_presenter_spec.rb
- spec/support/content_data_api.rb
[Trello card](https://trello.com/c/gAuhVJEp/1039-3-populate-organisation-filter-with-department-acronyms)
###What
Find the canonical list of all organisations' acronyms and populate them in the organisation filter.
###Why
So that we're able to support acronyms in the organisation filter
See evidence in https://trello.com/c/0rXbPvce
> Add Acronym to the organisation name

- app/assets/stylesheets/application.scss
Tighten up spacing
https://trello.com/c/OvTGt5uX/1087-1-adjust-the-padding-top-on-the-main-wrapper-to-10px
Meet designs
> Reduce space at top of screens.

- app/helpers/external_links_helper.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
- spec/helpers/external_links_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Adds a link to Google Analytics. The report is which search terms were used when users made internal site searches from a page.
Knowing the search terms will help us to identify what information the users are expecting to find on a given page.
---
> Add link to search terms

- app/helpers/external_links_helper.rb
- spec/helpers/external_links_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
We were sending the from and to values the wrong way round.
Fixes issue in https://github.com/alphagov/content-data-admin/pull/332
---
> Swap date params to GA report

- app/presenters/content_items_presenter.rb
https://trello.com/c/cx9UZewB/1064-1-bug-change-itemsto-lower-case-in-the-browser-title-tag
Change "Content Items" to "Content items" in page title.
Meet style guide
> Fix case on title tag for content page

- app/presenters/pagination_presenter.rb
- app/views/content/_table_data_description.html.erb
- spec/presenters/pagination_presenter_spec.rb
This formats numbers within the previous and next page links.
To make larger numbers easier to read.
---
> Add formatting to prev/next page links

- app/services/metrics_common.rb
Increasing the timeout on CDA's API client so that slow queries returned from CPM's API don't cause a timeout on production.
To address:
```
[0c6d156e-8dfe-4ca8-a064-0295a4559b2e] GdsApi::HTTPGatewayTimeout (URL: https://<REDACTED>/content?date_range=past-30-days&organisation_id=all&search_term=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fpublications%2F
Response body:
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
Request body:
):
[0c6d156e-8dfe-4ca8-a064-0295a4559b2e]
[0c6d156e-8dfe-4ca8-a064-0295a4559b2e] lib/gds_api/content_data_api.rb:22:in `content'
[0c6d156e-8dfe-4ca8-a064-0295a4559b2e] app/services/find_content.rb:21:in `call'
[0c6d156e-8dfe-4ca8-a064-0295a4559b2e] …
```
> Increase timeout

- app/helpers/external_links_helper.rb
- app/models/date_range.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/external_links_helper_spec.rb
- spec/models/date_range_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
Changes `to` and `from` methods of the DateRange model to return `Time` objects rather than strings. 
The date values are often manipulated before being used as strings and allows us to specify the format of the date string without re-parsing.
---
> Change DateRange to return Time objects

- app/helpers/time_select_helper.rb
- app/views/content/index.html.erb
- app/views/metrics/show.html.erb
- config/initializers/time_formats.rb
- spec/helpers/time_select_helper_spec.rb
Adds the TimeSelectHelper to create the time select options for both the metrics and content page. 
Too much logic embedded within the views. Helper removes duplicate code in the metric and content views and allows us to test it.
A presenter wasn't used as this relatively static code and presenters require more logic added to controllers.
---
> Add helper to generate time-select options

- app/assets/javascripts/application.js
- app/assets/stylesheets/content/_index.scss
- app/presenters/filter_presenter.rb
- app/services/find_content.rb
- app/views/content/_table_data_description.html.erb
- app/views/content/index.html.erb
- app/views/development/index.html.erb
- spec/features/index_page/index_filter_by_title_spec.rb
- spec/features/index_page/index_page_spec.rb
- spec/presenters/filter_presenter_spec.rb
https://trello.com/c/vbIFFSjh/1038-3-implement-basic-accessible-autocomplete-and-check-for-ie11-issues
This PR implements the accessible autocomplete component.
As agreed with Jeremy and Mark, when a user first sees the page (or when they clear their filters) we insert a blank option at the start so that the dropdown works as a dropdown, revealing the full content list. On submission we detect a hidden parameter the form sends and then auto-select their choice, or default to the "All document types" or "All organisations" option. This is because a selected item looks like a dropdown with just one option in it and a user who hasn't seen the full list may not consider deleting the content. 
This means that we are having to catch "all" as a document type where we didn't previously.
The …
> Implement accessibile autocomplete component for dropdowns

- app/helpers/organisations_helper.rb
- app/presenters/content_items_csv_presenter.rb
- spec/helpers/organisations_helper_spec.rb
Abstracts logic out for searching for organisation titles into OrganisationHelper module. Adds check for unknown organisation id and returns 'Unknown organisation' as name. Adds test cases.
Currently the content-performance-manager is returning content-items with organisation ids that are not returned by the `/api/v1/organisations` endpoint. Leads to errors when determining the organisation name when generating the CSV. The abstract allows for better testing of this behaviour.
---
> Handle unknown organisations during CSV download

- app/assets/stylesheets/content/_index.scss
- app/views/content/index.html.erb
https://trello.com/c/Rz0I7Byy/1110-3-re-write-the-table-without-the-helper
Stop using the helper
Give the table more breathing space
We should use the translations file for the table headers instead of hard coding them but I haven't addressed that here because there's a card in to potentially change them and they may need to diverge from headings used elsewhere.
The table helper isn't offering any advantage and it makes it more difficult to put html into the cells, which is a necessity to meet the layout we will need when we start sorting the table.
Jeremy and I took the opportunity to adjust the spacing so the content doesn't run as close to the edges as previously based on user feedback.
> Remove table helper

- spec/features/date_selection_spec.rb
- spec/features/index_page/index_filter_by_title_spec.rb
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- spec/presenters/content_items_presenter_spec.rb
- spec/presenters/filter_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/content_data_api.rb
- spec/support/request_stubs.rb
- spec/support/response_helpers.rb
- spec/support/shared/metadata.rb
- spec/support/shared/trend_percentages.rb
This refactors the request stubbing for content performance manager. GdsApi::TestHelpers::ContentDataApi module now only contains methods concerned with individual requests that can be made to the content-performance-manager. A new module RequestStubs contains methods to stub out all requests per each page in content-data-admin. All feature test should now use RequestStubs module instead of the ContentDataApi. Example responses have also been separated out into a separate module ResponseHelpers.
This simplifies the request stubbing in our feature tests. Will make it easier to make changes to the requests made by each pages in content-data-admin.
---
> Refactor request stubs

- app/assets/stylesheets/components/_info-metric.scss
- app/assets/stylesheets/metrics/_show.scss
- app/helpers/metrics_formatter_helper.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/show.html.erb
- config/initializers/time_formats.rb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/support/response_helpers.rb
https://trello.com/c/fNfu8Vl7/1122-3-add-reading-time-to-interface-front-end
This shouldn't be merged because we don't have the reading time metric yet, so it is faked here, but this PR:
- Adds reading time to the view
- Tests for it
- Adjusts CSS to make layout accommodate the new column
Helps users understand word count in a less abstract way
> Add reading time metric to interface

- app/presenters/content_items_csv_presenter.rb
- spec/features/index_page/index_page_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
Adding reading time column to the CSV of search results. Formatted in the `0h 0m` style.
Allows this data to be exported.
---
> Add reading time to csv

- app/helpers/metrics_formatter_helper.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/metrics_formatter_helper_spec.rb
- spec/support/request_stubs.rb
For some pages that do not have a word count, such as the Home page, we
are seeing a 500 error. This fix will trigger the component to not
render (as it does for no word count value).
Bug
https://content-data-admin.staging.publishing.service.gov.uk/metrics?date_range=past-30-days
---
> Fix reading time for no words

- app/views/components/_info-metric.html.erb
- app/views/components/_time-select.html.erb
- app/views/content/_page_title.html.erb
- app/views/content/_table_data_description.html.erb
- app/views/content/index.html.erb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/show.html.erb
- spec/features/index_page/results_pagination_spec.rb
- spec/features/index_page/user_analytics_spec.rb
- spec/features/metrics_page/user_analytics_spec.rb
- spec/support/request_stubs.rb
- spec/support/response_helpers.rb
Adding HTML data attributes to be using by Google Tag Manager and feature tests.
We use GTM to collect user analytics, data attributes and feature tests help make sure we don't break user tracking in future development.
---
> Add HTML data attributes for GTM

- config/routes.rb
- spec/routing/single_page_routing_spec.rb
Changes route config to prevent rails from parsing and removing the `.<format>` from the url. 
This fixes an issue whereby base paths with locale extensions are removed from the result. i.e. `base/path.cy` => `base/path`
---
> Change route for metrics to ignore format

- app/views/content/index.html.erb
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/user_analytics_spec.rb
[Trello card](https://trello.com/c/iZIdDLSt/1164-1-hide-the-link-download-csv-from-content-data-admin)
Hides the link to download a CSV from the Index Page
We have a few issues with the way we currently download the file, so
we are disabling it until we find a better solution, or improve the current
one.
> Hide download CSV link

- app/assets/images/question_mark_default.svg
- app/assets/images/question_mark_inverse.svg
- app/assets/stylesheets/content/_index.scss
- app/views/content/_table_data_description.html.erb
- app/views/content/index.html.erb
- config/locales/views/content/en.yml
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
https://trello.com/c/8STUqCTK/1111-3-rework-headers-in-the-table
https://trello.com/c/jFemNc0z/1143-3-sort-table-by-any-column-frontend
Reworks the table headers to allow each column to be sorted and the sorted
column to be highlighted visually and for screenreaders. By default it is
sorted by unique pageviews descending. On first click a column is sorted
descending, and on second click it switches to ascending.
This is the interface to allow users to access new ability to sort the table of contents
> Add icon and styles for results table sorting

- app/services/find_content.rb
I'm looking at this, as it led to a subtle issue where the CSV files
would be empty, if you filtered by all document types. FindContent is
used for both the HTML pages, and the CSV download, but this
conditional being removed only applied to the HTML page data.
To keep the Content Data API in the Content Performance Manager
consistent, this has been extended [1] to support 'all' as a special
value for document_type, similar to how 'all' is handled for
organisation_id.
With that change, the issue should be resolved, but also move the
special case for document_type in the Content Data Admin for
completeness and to make the code paths more consistent.
1: https://github.com/alphagov/content-performance-manager/commit/477bfea231de72892bae3fd213ae66acc93ca6b2
> Fix document type handling in find content

- app/views/content/_table_data_description.html.erb
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
Remove text from results spanning paginated pages
https://trello.com/c/gs3bac3N/1172-1-remove-1-to-100-of-text-from-the-table-summary
Reduce clutter
> Remove the 'X to Y' text from the table caption

- app/assets/stylesheets/content/_index.scss
- app/views/content/index.html.erb
Move clear link next to filter button on desktop
https://trello.com/c/AN09DD4T/1170-2-place-clear-all-filters-link-alongside-the-filter-cta
Visually better, gives more of a target.
> Move clear link next to filter button on desktop

- app/views/components/_chart.html.erb
- spec/features/metrics_page/user_analytics_spec.rb
[Trello card](https://trello.com/c/u8vri6WC/1149-3-data-attributes-for-gtm-for-the-content-item-page)
Make the name of the data attribute used by GTM more consistent with other HTML 
components. The old way will be reverted once GTM is deployed to production.
> Revert gtm data attributes single page

- app/views/content/_page_title.html.erb
- app/views/content/index.html.erb
- spec/features/index_page/user_analytics_spec.rb
[Trello card](https://trello.com/c/diMjPcK3/1136-3-data-attributes-for-gtm-for-the-index-page)
Restore old data attributes in order to deploy GTM to production
without losing any data.
We will revert these commits once the latest version to GTM is deployed.
> Restore GTM attributes to prevent deployment issues

- app/presenters/filter_presenter.rb
Remove repetitive organisation name/acronym combinations such as NS&I (NS&I)  or Companies House (Companies House). This removes extraneous whitespace and then compares the strings to determine whether to display the value from the acronym field.
Adds noise and no value, so needs removing
> Fix repetitive name/acronym combinations

- app/views/content/_page_title.html.erb
Fix display bug by decoding unusual characters encoded in slugs
https://trello.com/c/EHrM18LF/1548-bug-some-foreign-language-slugs-stretch-the-page-title-column-width-in-the-table-and-link-to-page-not-found
Page currently stretches and slugs are incomprehensible
> Unescape foreign characters on slugs

- app/assets/stylesheets/content/_index.scss
- app/presenters/content_row_presenter.rb
- app/views/content/index.html.erb
- spec/features/index_page/index_filter_by_title_spec.rb
- spec/presenters/content_row_presenter_spec.rb
This splits the satisfaction data in two at the presenter level,
adds tests for the correct responses, then presents the section in brackets
in a paler colour than previously (The colour has been checked for contrast/accessibility).
https://trello.com/c/RHEteDvs/1173-1-change-the-colour-of-the-number-of-responses-text-inside-the-table
De-emphasise response numbers
-
> Change colour to de-emphasise response values.

- app/views/layouts/application.html.erb
Send the User ID from Signon to Google Analytics
This is so we can monitor session behaviour of particular users and see when they're using different browsers/devices.
---
> Add user-uid to value to GTM

- app/assets/stylesheets/components/_chart.scss
- app/assets/stylesheets/components/_glance-metric.scss
- app/assets/stylesheets/components/_info-metric.scss
- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/metrics/_show.scss
- app/views/components/_chart.html.erb
- app/views/metrics/show.html.erb
https://trello.com/c/OUCjbciM/1204-2-spacing-adjustments-for-the-page-data-page
Change spacing on the data page for tidier visuals.
- This wraps the data page in a class so shared styles won't leak (seems to have been lost when it was present previously) and applies adjusted padding and margins to the page. 
- Makes a minor adjustment to the chart size as we no longer need to accommodate the legend so the space at the top is wasted.
Tidier page.
> Adjust spacing on data page

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/metrics/_show.scss
https://trello.com/c/OUCjbciM/1204-2-spacing-adjustments-for-the-page-data-page
Small spacing changes around the metadata and banner area
Meet design
> Adjust spacing to meet design.

- app/presenters/single_content_item_presenter.rb
- spec/presenters/single_content_item_presenter_spec.rb
[Trello](https://trello.com/c/r365wSrf/1178-3-user-satisfaction-chart-have-a-line-along-zero-rather-than-no-line-for-dates-before-data-exists)
We are getting errors in Staging when the we have no metrics for 
`useful_yes` and `useful_no`. This PR fixes this problem by converting
the metric to `0` before doing calculations.
This is consistent with the meaning of the metric as having no responses
about a particular page is the same as having 0.
> Fix nil satisfaction score value

- app/assets/stylesheets/components/_chart.scss
- app/views/components/_chart.html.erb
This reduces the height of the charts to reduce the page length.
It also reverts a previously introduced bug and gives the chart
enough height within its container to show the X axis value again.
https://trello.com/c/Y0SNB7jW/1246-1-adjust-the-height-of-the-chart-area
Bugfix & optimising page length
> Fix chart height

- Gemfile
- Gemfile.lock
- app/controllers/help_controller.rb
- app/views/content/index.html.erb
- app/views/help/show.html.erb
- app/views/layouts/application.html.erb
- config/locales/views/help/en.yml
- config/routes.rb
- spec/features/index_page/index_filter_by_title_spec.rb
- spec/features/index_page/sorting_spec.rb
- spec/rails_helper.rb
- spec/routing/help_routing_spec.rb
https://trello.com/c/D1sGgrBa/1144-5-view-help-text-in-table-frontend
- Move the help text into modals that appear on click
- Offer a non-js experience (also allows user to right click and open in new window)
- Support testing page elements that rely on js and add a test for modals
Title text was an interim measure, users have been seen struggling with it in testing as it only appears on hover, and even then is patchy. This is way better for accessibility and general usability.
> Move help text into modals

- app/views/content/index.html.erb
A final tweak to support the modals as per
https://trello.com/c/D1sGgrBa/1144-5-view-help-text-in-table-frontend
This adds an attribute to make it easier to differentiate between clicks on the sort link and the help link inside the table header.
> Add GTM data attribute to sort links

- spec/features/index_page/user_analytics_spec.rb
With the addition of modals for help we now have two links in the table
headers and specify the type on each. This adds the test for the tracking
on the sort link. The help link tracking is already tested for, it was just
repositioned.
https://trello.com/c/CipOJ9eK/1251-placeholder-add-tests-for-newly-added-gtm-tags
> Add test for sort link specific tracking

- app/views/metrics/show.html.erb
- spec/features/single_content_item_spec.rb
Hides the graph and table for User Satisfaction on the Page Metrics page.
User research shows that this is not useful at the moment. Hiding for
now until we can do some more thinking on it.
---
> Hide satisfaction score chart

- spec/features/metrics_page/user_analytics_spec.rb
This adds a feature to test to tracking of users clicking on the app name in the banner on the metrics page.
To make sure we don't break page attributes used by Google Tag Manager
---
> Add tests for app name tracking on metrics page

- Gemfile
- Gemfile.lock
- Procfile
- app/controllers/concerns/file_storage.rb
- app/controllers/content_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/content_csv_mailer.rb
- app/presenters/content_items_csv_presenter.rb
- app/views/content/export_csv.html.erb
- app/views/content/index.html.erb
- app/views/content_csv_mailer/content_csv_email.text.erb
- app/workers/csv_export_worker.rb
- config/environments/development.rb
- config/environments/test.rb
- config/routes.rb
- config/sidekiq.yml
- spec/features/index_page/export_csv_spec.rb
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/user_analytics_spec.rb
- spec/mailers/content_csv_mailer_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- spec/routing/content_routing_spec.rb
- spec/workers/concerns/file_storage_spec.rb
- spec/workers/csv_export_worker_spec.rb
This adds the ability to download CSV of the data on the content page via an link emailed to the user.
Changes include:
- Adding CSV download link on content page
- Add Sidekiq process and worker support
- Add CSV export Sidekiq worker that generate the CSV file, uploads to S3 and emails the user.
- Add ActionMailer to mail the user
- Add download request confirmation page when user clicks on download CSV
This is to provide CSV format of the data on the content page. Previously the user could download the file by streaming the download as it was generated. However, this had issues with server timeouts and quirks in browsers behaviours around streaming files. 
This approach aims to generate the file before making it available for the user to download. The CSV is generated asynchronously as …
> Add CSV download via email link

- app/views/content/export_csv.html.erb
The word 'receive' was corrected and mins was elongated to minutes.
---
> Fix spelling mistakes in CSV export view

- app/views/content/index.html.erb
- spec/features/index_page/export_csv_spec.rb
- spec/features/index_page/user_analytics_spec.rb
This removes the CSV download link from the content page. This is to prevent the CSV feature from being visible to the user, as GA has not been configured correctly. This will allow future deploys of the application and can re-enable the link once fixed.
---
> Disable CSV download link

- app/views/content/index.html.erb
- spec/features/index_page/export_csv_spec.rb
- spec/features/index_page/user_analytics_spec.rb
This reverts PR #439. This now makes the CSV download link visible for users, as previously disabled due to issues with analytics tracking.
---
> Revert "Disable CSV download link"

- config/sidekiq.yml
As the CSV is generated in memory, lowering the concurrency limit will prevent excessive memory usage with concurrent requests. This would have minimal user impact as they expect to wait for CSV
to be generated.
---
> Lower the sidekiq worker concurrency

- app/presenters/single_content_item_presenter.rb
- app/views/components/_glance-metric.html.erb
- app/views/metrics/_glance_metric.html.erb
- app/views/metrics/show.html.erb
- spec/components/glance_metric_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
https://trello.com/c/aWmUQbVq/947-2-fix-overflowing-figures-on-glance-metrics
Glance metrics were written to take input of an abbreviated number
and the appropriate labels, but we have never passed in the data in
that format. This means that the text is often stretching the limits
of its container and occasionally overflows. This change fixes that,
using a presenter to send the correct data to the glance metric
component where it is necessary to abbreviate.
(Ignore the data disparity, the rounding is correct but the sources in each image are different.)
> Abbreviate glance metric figures

- app/assets/stylesheets/content/_index.scss
https://trello.com/c/3ieHD7sB/1259-1-remove-underline-from-table-links
Remove underlines
Match design
> Remove underlines from links in the table on the index page.

- app/assets/stylesheets/components/_metadata.scss
- app/views/components/_metadata.html.erb
- spec/features/single_content_item_spec.rb
https://trello.com/c/NpoSJh3C/806-2-bug-fix-wrapping-on-page-metadata-at-tablet-size
The metadata was written as a list but has been formatted to look
like a simple table. This causes wrapping issues when the description
is long, so refactoring it into a table is both necessary and results
in cleaner code.
> Move metadata into a table

- app/controllers/content_controller.rb
- app/presenters/content_items_presenter.rb
- app/presenters/filter_presenter.rb
- app/views/content/index.html.erb
- spec/helpers/pagination_helper_spec.rb
- spec/presenters/content_items_presenter_spec.rb
- spec/presenters/filter_presenter_spec.rb
[Trello card](https://github.com/alphagov/content-data-admin/pull/454)
1. It moves out `FilterPresenter` from `ContentItemsPresenter`
2. It inlines code to retrieve `Organisations` and `DocumentTypes`
3. It simplifes code and tests to make them more readable
**Note**
In next PR we need to move into `ActiveModel` the code related to `Organisations` and `DocumentTypes` as we should not handle JSON directly within the application.
```ruby
def index
document_types = FetchDocumentTypes.call[:document_types]
organisations = FetchOrganisations.call[:organisations]
search_results = FindContent.call(search_params)
@presenter = ContentItemsPresenter.new(
search_results, search_params, document_types, organisations,
)
end
```
to:
```ruby
def index
search_results = FindContent.call(search_params) …
```
> Split filter and content presenter

- Gemfile
- Gemfile.lock
Clean up gem versions so we rely on Dependabot and tests to ensure 
incremental updates of our gems.
> Clean-up `Gemfile`: remove explicit versioning

- app/assets/stylesheets/components/_metadata.scss
- app/assets/stylesheets/components/_time-select.scss
- app/assets/stylesheets/content/_index.scss
- app/views/content/index.html.erb
https://trello.com/c/XltI9DFZ/1255-1-un-bold-headings-for-the-filters-on-the-index-page-and-adjust-the-font-size-inside-all-filter-boxes
- Remove bold to de-emphasise
- Reduce font size and add padding to keep a good hit size on selects
- Remove hr to bring both parts of the form together visually
Meet design, give less emphasis to the filters, make more text fit in dropdown options without wrapping.
> Tweak aesthetics on index page filters

- config/locales/defaults/en.yml
- config/locales/views/metrics/en.yml
https://trello.com/c/pAMwo89A/1534-2-add-opens-in-a-new-tab-text-to-links
Add text so user knows a new tab will open
Help users understand how to get back to the app afterwards
> Add text to make user aware links open new tabs

- app/assets/stylesheets/application.scss
Font loading is disabled since govuk-frontend v2.9.0 to ensure font file is not required twice for projects that rely on govuk_template. The typeface comes disabled from govuk_publishing_component and needs to be enabled in repos that don't rely govuk_template.
---
> Add nta font

- Gemfile
Remove duplicated `factory_bot_rails
This gem was in the Gemfile twice and bundler has been complaining about it.
Removed it from the production section as
we don't use it in production.
---
> Remove duplicated `factory_bot_rails`

- app/controllers/content_controller.rb
- app/workers/csv_export_worker.rb
- spec/features/index_page/export_csv_spec.rb
- spec/workers/csv_export_worker_spec.rb
Send a StatsD metric for elapsed time in seconds to generate the CSV
Adds `start_time` to the Sidekiq worker call.
The Sidekiq worker then uses this to send a counter to StatsD
with the number of seconds elapsed.
It also sends a second counter (marked slow) when the elapsed time is over 60 seconds, 
so we can calculate the percentage of slow downloads.
We want to know how long the users are waiting
for a CSV download.
---
Trello: https://trello.com/c/3Eg16r1C/1257-3-build-sli-grafana-dashboard
> Send a counter to StatsD for csv download time

- .rubocop.yml
- lib/tasks/lint.rake
This adds an import for the rules in govuk-lint gem into to the local `.rubocup.yml`. This allows us to use rubocop directly rather than through govuk-lint cli which adds no extra functionality.
Benefits include:
- Speeds up linting, by enabling parallel checking
- Lower overhead for new developers who are used to rubocop
- Better compatibility with developer environments - as most linting tools interface with rubocop
---
> Use rubocop directly

- .gitignore
- config/environments/development.rb
- config/environments/test.rb
Support local environment variables for `development` and `test`
environments, defined in `config/local_env.yml`.
This is the same as `content-performance-manager` which supports
it in `development`.
The file is git-ignored so we can all have different ones.
Local (mac not VM) development is difficult.
This enables you to have local environment variables.
This is very useful if, for instance, you want your database to be configured in 
a non-standard way (i.e. in Docker)
You don't have to use it but it makes life easier if you do.
---
> Support `local_env.yml`

- app/assets/javascripts/core/filtertoggle.js
- app/assets/stylesheets/content/_index.scss
- app/views/content/index.html.erb
https://trello.com/c/I23kWX2p/1327-show-filter-didnt-work-the-system-reads-this-but-its-not-visible
Using the visually-hidden class means that the hidden content
was exposed to screenreaders where it made no sense. This adds
a new class to hide content and implements it across the view
and the javascript.
Improve the screenreader experience
No screenshots as there is no visible change.
> Switch out visually-hidden class

- app/workers/csv_export_worker.rb
- spec/workers/csv_export_worker_spec.rb
Remove the `monitor.csv.download.seconds.slow` counter
We were sending this counter to calculate the
percentage of slow downloads.
This is no longer neccessary, as we are going,
to use percentiles of the raw metric, so the code is redundant.
Use GovukStatsd `timing` not `count`
refactor the call to use `timing` with
the number of milliseconds.
I called the wrong method when I implemented the
CSV download time Statsd call.
Trello: https://trello.com/c/3Eg16r1C/1257-3-build-sli-grafana-dashboard
---
> Fix download times metrics

- app/views/content/index.html.erb
https://trello.com/c/VPwvpZpm/1328-search-box-is-always-selected-by-default
Remove focus state from searchbox on load
Focusing the user directly on the search means they may miss the date filters. This is particularly confusing for assistive tech as a screenreader will start reading the page from the focused position, so it would miss the headings on the page by default.
> Remove default focus state from searchbox

- app/views/content/_table_data_description.html.erb
- config/locales/defaults/en.yml
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
https://trello.com/c/FOGiwFqQ/1330-add-all-document-types-to-the-sentence-summary
- display "all document types" when it is chosen
- downcase the generic terms "all document types" and "all organisations"
- capitalise initial on "No matching results"
- change double quotes to single quotes
- update tests to reflect new expectations
Makes it more explicit what is being shown, improves readability slightly.
> Tidy up results table description text

- lib/gds_api/content_data_api.rb
- spec/support/content_data_api.rb
Rather than the Content Performance Manager, following on from the
work to change the name of the Content Performance Manager to the
Content Data API.
Currently, the domain for the Content Performance Manager was being
overwritten in AWS Staging and AWS Production, but with this change,
that will become unnecessary.
---
* ~~Added/updated relevant documentation.~~
> Switch to using `content-data-api` with Plek

- lib/gds_api/content_data_api.rb
Rather than the CONTENT_PERFORMANCE_MANAGER_BEARER_TOKEN, as part of
the work to rename the Content Performance Manager to the Content Data
API.
This change is dependent of this environment variable becoming
available through changing govuk-puppet.
This depends on https://github.com/alphagov/govuk-puppet/pull/9008
---
* ~~Added/updated unit tests.~~
* ~~Added/updated feature tests.~~
* ~~Added/updated relevant documentation.~~
> Change to use the CONTENT_DATA_API_BEARER_TOKEN

- app/presenters/content_items_csv_presenter.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- An update has been made to reflect the new link
- content-data replaces content-data-admin
Trello: https://trello.com/c/mr3p168v
> Update content data link when exporting CSVs

- app/views/components/_chart.html.erb
- app/views/content/_page_title.html.erb
- app/views/content/index.html.erb
- spec/features/index_page/user_analytics_spec.rb
- spec/features/metrics_page/user_analytics_spec.rb
Remove redundant tracking data attributes.
Some existing data attributes were renamed for consistency as part of https://trello.com/c/spmbz9Yl. We temporarily kept the old ones alongside the new ones so that we wouldn't lose any tracking during the switchover.
Trello: https://trello.com/c/ddvtKkCq/1365-1-delete-some-data-attributes-that-are-no-longer-needed
---
> Delete redundant tracking data attributes

- app/presenters/single_content_item_presenter.rb
- config/locales/defaults/en.yml
- spec/presenters/single_content_item_presenter_spec.rb
Fix inflection 'out of 1 responses'
When there's exactly 1 response, the text under the user
satisfaction score in the at-a-glance section says
"Users who found the page useful, out of 1 responses". This is ungrammatical
as it should be singular '1 response'.
Coming soon
Trello: https://trello.com/c/vO3DkpTk/1362-2-fix-inflection-out-of-1-responses-in-at-a-glance-user-satisfaction-score
---
> Fix inflection 'out of 1 responses'

- app/helpers/external_links_helper.rb
- spec/helpers/external_links_helper_spec.rb
Add &document_type=homepage to Feedex Uri
When sending users to the feedback explorer for the GOV.UK homepage,
the users were seeing feedback for all content (under '/').
This PR adds the document type of homepage to the query string to limit
the results to what we want.
---
> Add &document_type=homepage to Feedex Uri

- config/environments/development.rb
- config/environments/test.rb
Remove support for `local_env.rb`
I added this support to help with local development.
Turns out this is unnecessary as [direnv](https://direnv.net/) will do the job.
---
> Remove support for `local_env.rb`

- app/views/components/_glance-metric.html.erb
- spec/features/single_content_item_spec.rb
- spec/support/response_helpers.rb
- Add delimiter to comparison data
The comparison data does not show a delimiter, so this PR fixes this.
> Show comma separator in comparison data

- config/locales/defaults/en.yml
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Renamed the user satisfaction score to 'users who found page useful'
To better reflect the metric
---
> Rename satisfaction score

- config/locales/defaults/en.yml
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
- spec/features/single_content_item_spec.rb
Renamed 'searches from the page' to 'searches from page'
For consistency with 'users who found page useful' metric
---
> Rename searches from the page

- app/presenters/single_content_item_presenter.rb
- app/views/components/_glance-metric.html.erb
- app/views/components/_info-metric.html.erb
- app/views/metrics/_glance_metric.html.erb
- app/views/metrics/_metric_section.html.erb
- spec/components/glance_metric_spec.rb
- spec/components/info_metric_spec.rb
When a content is published there is no data present until the ETL process
executes. Currently, the page does not hint that there is no data present,
this may confuse users to think that the page maybe broken.
Now the page is styled like other pages for consistency and displays the sentence,
no data, to make it more clear.
Trello card: https://trello.com/c/JOfeWXgS
> Improve layout of page data page which has no data to show

- app/controllers/metrics_controller.rb
- app/views/errors/404.html.erb
- config/locales/views/errors/en.yml
The 404 page now has a header, which follows the layout of other pages.
Trello: https://trello.com/c/1EfhcV4y
> Replace 404 page not found error page

- app/assets/stylesheets/metrics/_show.scss
https://trello.com/c/ExASFw8R/1453-1-not-enough-padding-on-the-right-hand-side-of-the-action-links-box
Introduce extra padding
To avoid it looking bad when the link is long enough to wrap
> Add padding to link

- app/assets/stylesheets/metrics/_show.scss
- app/views/metrics/_content_metrics.html.erb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
https://trello.com/c/76VOZ7pD/1425-3-update-page-content-metrics-layout
This is the first step towards adding document info to multi part pages. It adjusts
the layout of the metrics about the content, including PDFs. PDFs will later be
handled by the document structure components so this is an interim solution to keep
them appearing but the layout will remain for the other two metrics.
Reduce use of space, bring in line with the design for document structure content
> Update layout of content metrics

- app/views/layouts/application.html.erb
https://trello.com/c/SorbEsQE/1459-add-a-switch-app-link-to-the-header-and-make-sure-that-the-profile-name-links-to-the-right-place-in-signon
Adds a link to signon so users can switch apps more easily.
The name already links here but users are not recognising that. This brings us in line with what the Publisher team do.
> Add explicit link for switching apps in Signon

- app/views/metrics/_content_metrics.html.erb
- spec/features/metrics_page/user_analytics_spec.rb
https://trello.com/c/76VOZ7pD/1425-3-update-page-content-metrics-layout
A tiny change to add tracking to the reworked page content metrics section.
> Add tracking to content metrics section

- app/assets/stylesheets/metrics/_show.scss
Update so that the overrides only affect full width view
Mobile view is currently broken - see screenshot
> Fix mobile layout on content metrics

- app/views/content/export_csv.html.erb
Removed 'should' and a negative contraction
Because they can be ambiguous for users
---
> Change text to follow GOV.UK style

- app/views/content_csv_mailer/content_csv_email.text.erb
- spec/mailers/content_csv_mailer_spec.rb
Told users that link expires after 7 days
So they know it will stop working and they should use it before then
---
> Update CSV email to say when link expires

- app/models/calculator/trend_percentage.rb
- spec/models/calculator/trend_percentage_spec.rb
If the previous value is nil, the trend percentage calculate threw an error. This puts gaurds in for nil values and adds more unit tests.
---
> Fix nil in trend percentages

- app/views/content/index.html.erb
Bugfix:  It is necessary to add blank entries to the lists for the dropdowns but this was being added in two places, resulting in a duplicate.
> Remove blank entry from dropdown

- app/views/components/_info-metric.html.erb
https://trello.com/c/pXZS4vwK/1477-2-fix-formatting-for-no-data-for-satisfaction-score
This reworks the info metrics component to make the indentation more logical and ensure that html entities are encapsulated properly within logic paths. An incorrect termination of a div had caused layout problems in cases where no data is available.
> Fix layout bug

- app/helpers/external_links_helper.rb
- app/presenters/single_content_item_presenter.rb
- spec/helpers/external_links_helper_spec.rb
- spec/support/response_helpers.rb
- spec/support/shared/metadata.rb
Adds a link `Edit in Content publisher` when the `publishing_app`
is `content-publisher`.
What are the proposed changes?
As a convenience to users
---
> Add link to edit in content publisher.

- app/presenters/content_items_csv_presenter.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/_content_metrics.html.erb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
- spec/presenters/content_items_csv_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/response_helpers.rb
- spec/workers/csv_export_worker_spec.rb
Rename total_words to word_count to be consistent.
---
> Rename total_words to word_count to be consistent

- app/presenters/content_items_csv_presenter.rb
- spec/presenters/content_items_csv_presenter_spec.rb
This fixes a bug whereby word count is not available in the CSV export due to incorrectly referencing of `words` instead of `word count`.
---
> Fix word count metric for CSV export

- app/assets/stylesheets/components/_info-metric.scss
Fix the font size on the short context in the info metric component
(Ignore the missing comparison data in the "after" screenshot, this is because the dataset on my dev environment is lacking.)
> Fix 'number of responses' font size

- config/locales/views/components/en.yml
- spec/features/index_page/index_page_spec.rb
Took out the repetition of 'page data' (it used to appear in the kicker and the header)
Titles are more meaningful if they're not repetitive
---
> Change heading to be less repetitive

- app/views/content/_table_data_description.html.erb
https://trello.com/c/DmEHFLCa/1514-capitalisation-of-acronyms-in-summary-above-index-page-table
We previously made a conscious decision to downcase document type names, but this has led to items with abbreviated terms or acronyms coming out incorrectly, eg html instead of HTML. This PR adds logic to the presenter to exclude the relevant terms from being downcased.
> Fix sentence case for document types in table summary

- config/locales/defaults/en.yml
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/results_pagination_spec.rb
- spec/features/single_content_item_spec.rb
- spec/presenters/chart_presenter_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
Change the wording "pageviews" to "page views" and update related tests
https://trello.com/c/H3nPNXVA/1481-3-change-pageviews-to-page-views-to-reflect-ga-change-plus-its-nicer
> Change 'pageviews' to 'page views' and update related tests

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/content/_index.scss
https://trello.com/c/Pd4TSrme/1523-fix-page-title-styling-in-table-on-comparison-page
Add bold and remove underline on page links
Match the index page
> Style page links on compare page to look the same as index page

- app/views/documents/children.html.erb
https://trello.com/c/f7JJpYlr/1521-fix-links-for-time-selection-on-comparison-page
Fix date options
> Match document time select options to index time select options

- app/presenters/content_row_presenter.rb
- spec/features/document_children_page/no_data_spec.rb
- spec/presenters/content_row_presenter_spec.rb
This fixes a bug where the table row presenter doesn't know how to process nils for useful_yes, useful_no, satisfaction or searches. Now it will return the string 'No data'.
---
> Fix table row presenter with nil data

- app/views/layouts/application.html.erb
- spec/features/document_children_page/documents_children_page_spec.rb
- spec/features/index_page/index_page_spec.rb
- spec/features/index_page/user_analytics_spec.rb
- spec/features/metrics_page/user_analytics_spec.rb
https://trello.com/c/sviPxTmq/1524-move-content-data-from-phase-banner-to-header
Change header to say Content Data (with a capital on Data)
Remove Content data from the phase banner
Improve link clarity, remove unclickable app name
> Move app name into header and remove from banner, adjust tests accordingly

- spec/features/document_children_page/no_data_spec.rb
The test is incorrectly looking for `Content data` when it should be `Content Data` because we moved the application name to the navigation bar.
---
> Fix tests for document children with no data

- app/assets/stylesheets/content/_index.scss
- app/views/content/index.html.erb
https://trello.com/c/R26631io/1486-3-design-a-more-helpful-error-message-for-no-results-found
Add guidance text when queries return no results
I considered putting this into the localisation files for ease of updating, but it needed too much markup to make it look right.
Help users find their content
> Add guidance text when there are no results on index page

- app/assets/stylesheets/compare/_show.scss
https://trello.com/c/gPmlYaoC/1519-fix-styling-of-search-link-on-comparison-page
Align search link better
> Align search link to match other pages better

- app/views/documents/_table.html.erb
Replace it with the actual number of children.
---
* ~~Added/updated unit tests.~~
* ~~Added/updated feature tests.~~
* ~~Added/updated relevant documentation.~~
> Remove hardcoded 6 from the document children table

- app/presenters/content_row_presenter.rb
- app/presenters/document_children_presenter.rb
- spec/support/response_helpers.rb
The API references the parent document with a sibling order of 0, instead of '-'. This fixes the logic selecting the parent and the formatting the order value in the table.
---
> Fix parent sibling order reference

- app/presenters/document_children_presenter.rb
- spec/presenters/document_children_presenter_spec.rb
A parent guide page includes the first section the title. This means the document children page displays a section name in the header for guides. This a small fix to remove the extra section
name. For guides with multiple colons, it removes just the last section.
---
> Fix guide titles for document children pages

- app/helpers/external_links_helper.rb
- spec/features/single_content_item_spec.rb
- spec/helpers/external_links_helper_spec.rb
So "Manuals Publisher" rather than "Manuals publisher", which is more
consistent with how the application name is presented elsewhere.
---
* ~~Added/updated relevant documentation.~~
> Capitalise each word in the name of publishing apps

- lib/gds_api/content_data_api.rb
There are some timeouts occuring when generating CSV files. I believe
the default timeout is 4 seconds in the GDS API Adapters, so increase
this to 60 seconds (which matches the NGinx proxy read timeout).
---
> Increase timeout for the Content Data API

- app/controllers/documents_controller.rb
- app/presenters/document_children_presenter.rb
- spec/features/document_children_page/no_data_spec.rb
- spec/features/document_children_page/sorting_spec.rb
- spec/presenters/document_children_presenter_spec.rb
- spec/support/response_helpers.rb
We now find the parent by base path, rather than relying on sibling order.
---
> Use parent_base_path to find parent in comparison page

- app/views/layouts/application.html.erb
- spec/features/index_page/index_page_spec.rb
The title of the page should render with the suffix of GOV.UK Content Data instead of GOV.UK Publishing. This is consistent with the wording in the header.
---
> Update page title suffix to GOV.UK Content Data

- app/presenters/document_children_presenter.rb
- spec/presenters/document_children_presenter_spec.rb
This adds travel advice to the document types which the heading is formatted. This is removing a page section from the main content title i.e. `Travel to Spain: Overview` -> `Travel to Spain`.
---
> Fix heading format of travel advice comparison page

- app/assets/stylesheets/components/_related-actions.scss
- app/helpers/document_children_helper.rb
- app/presenters/single_content_item_presenter.rb
- app/views/components/_related-actions.html.erb
- app/views/metrics/show.html.erb
- spec/components/related_actions_spec.rb
- spec/features/metrics_page/document_children_link_spec.rb
- spec/helpers/document_children_helper_spec.rb
- spec/presenters/single_content_item_presenter_spec.rb
- spec/support/request_stubs.rb
- spec/support/response_helpers.rb
- spec/support/shared/metadata.rb
This adds the link from page data pages to the comparison pages. The link will only show if there is available content.
---
> Link to comparison page

- config/locales/defaults/en.yml
Letting users know that they need Google Analytics to see the search terms
For consistency with 'about number of feedback comments'
---
> Add that users need a GA account in about searches from page

- .rubocop.yml
- .scss-lint.yml
- Gemfile
- Gemfile.lock
- lib/tasks/lint.rake
As govuk-lint is soon to be deprecated. The style rules will remain the same.
> Replace govuk-lint with rubocop-govuk & scss_lint-govuk

- app/helpers/external_links_helper.rb
As Google Analytics has the paths in the lower case.
> Link to GA with a lower case base_path

- app/assets/stylesheets/components/_glance-metric.scss
- app/views/components/_glance-metric.html.erb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- spec/components/glance_metric_spec.rb
- spec/features/single_content_item_spec.rb
As it could be misleading now that the way data is collected through
Google Analytics has changed. Also tweak the CSS to adjust for the
removal of the comparison data.
---
> Disable showing comparison data

- app/controllers/application_controller.rb
- app/helpers/time_select_helper.rb
- app/models/date_range.rb
- app/views/components/_time-select.html.erb
- app/views/content/index.html.erb
- app/views/documents/children.html.erb
- app/views/metrics/_metric_header.html.erb
- app/views/metrics/_metric_section.html.erb
- app/views/metrics/show.html.erb
- config/locales/views/metrics/en.yml
- spec/components/time_select_spec.rb
- spec/helpers/time_select_helper_spec.rb
- spec/models/date_range_spec.rb
This PR allows a user to manually update the `date_range` param to a format such as `march-2020` to see data for this specific time frame.
[dependent content-data-api PR](https://github.com/alphagov/content-data-api/pull/1442)
[trello](https://trello.com/c/OKYeyYHe/1799-5-allow-content-data-api-and-content-data-admin-to-return-data-by-month)
> Allow content data to be requested by month

- .rubocop.yml
- Rakefile
- app/helpers/pagination_helper.rb
- app/views/content/index.html.erb
- lib/tasks/lint.rake
- spec/helpers/pagination_helper_spec.rb
https://trello.com/c/5Gob6WUL/147-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
This adds a new 'lint' rake task that runs as part of a default call to
'rake'. Having linting run locally by default makes it easier to catch
build issues, and is a prerequisite for moving to GitHub Actions, since we
want to avoid listing lots of separate build steps.
> Extend 'default' task with RuboCop linting

- Rakefile
- Otherwise we see errors like this on deploys to production environments:
```
13:53:53 *** [err :: ip-10-12-6-44.eu-west-1.compute.internal] rake aborted!
13:53:53 *** [err :: ip-10-12-6-44.eu-west-1.compute.internal] Don't know how to build task 'default' (See the list of available tasks with `rake --tasks`)
13:53:53 *** [err :: ip-10-12-6-44.eu-west-1.compute.internal] /data/vhost/content-data/releases/20200519125347/Rakefile:4:in `<top (required)>'
```
> Only clear the default Rake task settings in development and test

- .github/dependabot.yml
- package.json
In accordance with [RFC 126], we're configuring Dependabot to only
raise Pull Requests for the following three categories:
1. Security updates
2. Internal libraries
3. Framework libraries
Things have moved on slightly since the RFC; we're now using
[GitHub native] configs rather than the legacy `.dependabot`
approach. The syntax is slightly different to the example config
provided in the RFC but most of it is easily transferable.
We've handled (2) and (3) in config, and have set it to only raise
PRs for direct updates, i.e. updates to subdependencies of the
named dependencies will not raise PRs.
We've chosen a `govuk*` wildcard to cover things like
`gds-api-adapters` and `govuk_app_config` and other unknown future
dependencies. Having `govuk` as a [suffix is not encouraged][wildcards]
so …
> Add Dependabot configuration

- Gemfile
- Gemfile.lock
Content Data uses the accessible autocomplete component which was removed in version 18.
Arose from https://github.com/alphagov/govuk-developer-docs/pull/2830
> Pin govuk_publishing_components to 17.21.0

- app/controllers/metrics_controller.rb
The 404 page was previously converted from a static HTML file to a ERB template. However, the render statement wasn't updated to render the erb template so was returning the file un-rendered as plain/text.
> Fix rendering of 404 page

- Jenkinsfile
Points the app to run against Postgres version 13, instead of the
old version 9.6. Postgres 13 runs on the port 54313.
Trello:
* https://trello.com/c/QQf4LjT6/14-content-data-admin
* https://trello.com/c/yaBLaC1O/957-upgrade-content-data-admin-postgres-96-13
> Use Postgres 13 in CI 

- config/environments/development.rb
This development config (file_watcher) was previously enabled in a Rails bump upgrade
[1], however as we don't bundle the listen Gem [2], this config just throws a requirement error.
[1]: https://github.com/alphagov/content-data-admin/commit/ea910176d1b22a0267344ed534185f62a8372e3b#diff-d3c4b3f41072daa416f1920511e9b2e26caea8c5cec0a14cb9508589a4dafa47R69
[2]: https://github.com/guard/listen
> Fix development dependancy error

- app/assets/javascripts/application.js
- app/assets/javascripts/survey-banner/survey-banner.js
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
Add a call-to-action banner to complete a survey on users' experience of the Content Data tool.
The banner can be dismissed and this is recorded in a cookie.
> Add survey banner

- app/assets/javascripts/survey-banner/survey-banner.js
The script that handles showing and hiding the survey banner breaks on pages other than the index page, because it assumes the element is present.
This fix simply checks that the element is present before attempting to show or hide it.
> Fix Javascript error when survey banner turned off

- lib/gds_api/content_data_api.rb
- spec/support/content_data_api.rb
Usage of `Plek.current` was marked as deprecated in https://github.com/alphagov/plek/pull/94, therefore we should remove uses of the old syntax before upgrading Plek, else we'll log lots of deprecation warnings.
See also https://github.com/alphagov/publishing-api/pull/2158
> Replace `Plek.current` with `Plek.new`

- .dockerignore
- Dockerfile
- config/application.rb
- Parameterise the Ruby version.
- Precompute the [bootsnap](https://github.com/Shopify/bootsnap#bootsnap-) bytecode and path caches so that bootsnap is effective when running the app from the container image.
- Remove some hard-coded paths.
- Clean up `.dockerignore`.
- Make better use of `WORKDIR`.
- Remove the now-redundant `bundle exec` from the default command.
Tested: builds and comes up healthy on the integration Kubernetes cluster.
> Clean up Dockerfile.

- Gemfile
This way the bootsnap caches are much more likely to be effective.
See https://github.com/Shopify/bootsnap#usage.
> Set `require: false` for bootsnap.

- Gemfile
- Gemfile.lock
This is an indirect dependency, and was only included because we needed to pin the version for a while. The unpinning has happened, so we can now delete it as an explicit dependency.
> Remove 'mail' as a direct dependency

- config/application.rb
Use GOVUK_ENVIRONMENT_NAME for the environment name instead of ERRBIT, as we don't have that env var available in EKS. They should be the same anyway.
> Fix configuration of GOV.UK environment name

- Gemfile
- spec/features/document_children_page/documents_children_page_spec.rb
This gem swallows exceptions raised by our app, and replaces them with error pages. This makes it very difficult to debug failures in our feature specs, as we no longer see a stack trace.
Before this change, here's what the failures on [this Dependabot PR](https://github.com/alphagov/content-data-admin/pull/1230) look like:
```
Failures:
1) /content Filter by title / url renders the filtered items
Failure/Error: fill_in "Search for a title or URL", with: "title"
Capybara::ElementNotFound:
Unable to find field "Search for a title or URL" that is not disabled
2) /content Filter by title / url populates the search field with the current filter
Failure/Error: fill_in "Search for a title or URL", with: "title"
Capybara::ElementNotFound:
Unable to find field "Search for a title or URL" that is …
```
> Only include better_errors gem in development env

- app/services/find_content.rb
This is now defined in govuk helm charts: https://github.com/alphagov/govuk-helm-charts/pull/1636
https://trello.com/c/MU9KwkRP/3368-improve-performance-of-content-data-csv-exports-3
> Make page size an env var

- Gemfile
- Gemfile.lock
- app/controllers/metrics_controller.rb
- app/models/user.rb
- app/services/email_api/page_subscriptions_client.rb
- app/services/email_api/page_subscriptions_response.rb
- app/views/metrics/_email_subscriptions.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/factories/users.rb
- spec/features/single_content_item_email_subs_spec.rb
- spec/services/email_api/page_subscriptions_client_spec.rb
* Show a section with email subscription numbers from the `email-alert-api` on the `/metrics` page.
> Add email subscription metrics

- app/presenters/siteimprove/policy_issues_presenter.rb
Reported crash on certain pages: https://govuk.sentry.io/issues/4893720921/?project=1259363&query=&referrer=project-issue-stream
> Prevent crash if policy not found

- app/views/components/_ga4_notice.html.erb
- app/views/content/export_csv.html.erb
- app/views/content/index.html.erb
- app/views/content_csv_mailer/content_csv_email.text.erb
- app/views/documents/children.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
The new Google GA4/BigQuery product we are migrating to are not direct mappings of the old (Universal Analytics) metrics and the numbers may vary.
Adding this notice should hopefully make it clear to the user of the changes in case they see a significant change in pattern in the GOV.UK pages they are monitoring.
This has been tested on Integration - see screenshots below.
Before:
After:
Before:
After:
Trello card: https://trello.com/c/7z6fJUBD/3381-1-update-content-data-admin-with-google-ga4-migration-notice
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …
> Add GA4 migration notice

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/concerns/file_storage.rb
- app/workers/csv_export_worker.rb
- lib/partial_sitemap_generator.rb
- lib/tasks/sitemaps.rake
- spec/features/index_page/export_csv_spec.rb
- spec/lib/partial_sitemap_generator_spec.rb
- spec/rails_helper.rb
- spec/workers/concerns/file_storage_spec.rb
- spec/workers/csv_export_worker_spec.rb
Converts Content Data Admin to use S3 rather than Fog, and adds a rake task to generate partial sitemaps to be ingested by Siteimprove.
> Add Siteimprove Sitemap Generator

- app/assets/stylesheets/components/_accessible-autocomplete.scss
These are not supported in Dart Sass.
This has been tested in Integration - see below.
Related PR - https://github.com/alphagov/content-data-admin/pull/1373
Trello card: https://trello.com/c/kZ3qj2TI/3405-3-migrate-content-data-admin-to-dart-sass
> Update asset-path helper

- app/views/content/export_csv.html.erb
- app/views/content_csv_mailer/content_csv_email.text.erb
Pointing users to the Support app form means requests can be triaged appropriately through Zendesk, and is also consistent with how we manage user requests for other apps.
Trello card: https://trello.com/c/DboQcYLw/3431-2-point-contact-data-users-needing-help-to-a-form-in-the-support-app
> Update contact details for user downloads

- app/views/content_csv_mailer/content_csv_email.text.erb
The links are not being rendered correctly and appear in the email as raw HTML.
Trello card: https://trello.com/c/DboQcYLw/3431-2-point-content-data-users-needing-help-to-a-form-in-the-support-app
> Fix links in csv export email

- app/views/metrics/_siteimprove_issues.html.erb
(matching other siteimprove tables)
> Update broken links table so left column is fixed

- app/views/content_csv_mailer/content_csv_email.text.erb
- config/locales/defaults/en.yml
Some issues with the data were reported. We don't think we should email users via Notify, because we can't tell how many of the potential 4,599 users are actually actively using the app (access to the app is given by default). This message will only be seen by users who are actually using the tool.
> Update the GA4 banner with details about inconsistencies

- app/views/metrics/_email_subscriptions.html.erb
- config/locales/defaults/en.yml
It doesn't make sense to show the email statistics for finders because the way they handle email subscriptions is considerably more complex than normal pages, and there are very few of them. So to avoid misleading users, simply let them know the basics for finders (this is a finder, it won't trigger email alerts itself, there may be multiple subscriber lists to it).
https://trello.com/c/ZM53KHEM/2406-consider-how-email-alert-api-reports-mailing-list-sizes-for-finders
> Finder note email stats

- app/views/content_csv_mailer/content_csv_email.text.erb
- config/locales/defaults/en.yml
We have now fixed the issues with the data, and have completed migrating all the metrics to GA4.
Before:
After:
> Update GA4 migration banner

- app/views/layouts/application.html.erb
This allows us to implement basic GA4 tracking on all pages of the app. It is configured using the following environment variables:
GOOGLE_TAG_MANAGER_GA4_ID
GOOGLE_TAG_MANAGER_GA4_AUTH (integration only)
GOOGLE_TAG_MANAGER_GA4_PREVIEW (integration only)
If only the `GOOGLE_TAG_MANAGER_GA4_ID` is set then the default environment of the GTM container will be used.
If `GOOGLE_TAG_MANAGER_GA4_AUTH` and `GOOGLE_TAG_MANAGER_GA4_PREVIEW` are set then the specified GTM container environment will be used - specifically for testing the configuration in Integration before rolling out to Production.
This app already has UA enabled and we will need to do dual tracking until we're sure the GA4 implementation is working as expected and have the relevant reporting in place.
This has been successfully …
> Setup Google Tag Manager

- app/workers/csv_export_worker.rb
- spec/features/index_page/export_csv_spec.rb
- spec/workers/csv_export_worker_spec.rb
Prometheus scrapes data from Pushgateway every 60 seconds which means it continues to record the same metric until another one is sent. Adding a distinct label will allow us to filter out duplicate values in Grafana.
As you can only register a histogram once, we have to create a new one which allows us to add a label as part of it's setup.
Related PR: https://github.com/alphagov/content-data-admin/pull/1426
Trello card: https://trello.com/c/SQro2G8f/3476-monitor-how-long-content-datas-csv-exports-take-5
> Add distinct label to CSV export metrics

- app/controllers/metrics_controller.rb
- app/models/user.rb
- app/views/metrics/_email_subscriptions.html.erb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/factories/users.rb
- spec/features/single_content_item_email_subs_spec.rb
- spec/support/request_stubs.rb
Since it was added, the email stats section of content data admin pages has always been gated behind a specific permission. This was added during development to test the feature without exposing it to departments. This PR removes the need for that permission, and updates the copy displayed in the feature.
> Remove Permission for Email stats

- app/helpers/external_links_helper.rb
- app/presenters/single_content_item_presenter.rb
- app/views/metrics/show.html.erb
- config/locales/defaults/en.yml
- spec/features/single_content_item_spec.rb
- spec/helpers/external_links_helper_spec.rb
Removed a link to UA because we are migrating to GA4. This link is now redundant.
Before: 
After:
https://trello.com/c/QacJuXBT/3490-remove-a-link-to-universal-analytics-in-content-data-1
> Removing link to ua

- config/application.rb
Both environment variables are set to the same value. GOVUK_ENVIRONMENT is used more frequently, renaming for consistency.
> Use GOVUK_ENVIRONMENT instead of GOVUK_ENVIRONMENT_NAME

- config/routes.rb
We are getting various errors including `ActionView::Template::Error`, `Errno::ENOENT`, `URI::InvalidComponentError` in Sentry for those routes.
Those routes were added temporarily in https://github.com/alphagov/content-data-admin/pull/3 for development purposes and should not be available in production. As a result of this change, users will get a 404 Not Found error, which are not logged in Sentry. This is consistent to the approach in Whitehall: https://github.com/alphagov/whitehall/blob/27708f3/config/routes.rb#L462
Related Sentry issues:
- https://govuk.sentry.io/issues/5718963917/events/aaa3ac5f7aca4398b1c5b3d7a48280a0/
- https://govuk.sentry.io/issues/6012931939/events/4eb7e3bb81a84321b8f830e675dd051c/
- https://govuk.sentry.io/issues/5954145258/events/ed5d2f84ad10497780f89dca4d5ce2 …
> Scope /component-guide to development and test

- app/presenters/siteimprove/policy_issues_presenter.rb
- spec/presenters/siteimprove/policy_issues_presenter_spec.rb
There's a few examples where the API response doesn't have `note` attribute causing: 
```
NoMethodError
undefined method `gsub!' for nil (NoMethodError)
note.gsub!(/https:\/\/(.+)/, "[https://\\1](https://\\1)")
^^^^^^
```
https://govuk.sentry.io/issues/6330840181/events/6958f220ade349e3940088ce42af1e50/
Examples:
- check-the-patents-journal
- check-national-insurance-record
- get-access-evisa
> Don't return policy description if there's not note attr

- .github/workflows/ci.yml
- .github/workflows/copy-pr-template-to-dependabot-prs.yml
**As a** platform engineer
**I want** our deployment process for our app repos to handle concurrent releases
**so that** we avoid issues with incorrect ordering of releases
https://github.com/alphagov/govuk-infrastructure/issues/2123
> Configure CI workflow to handle concurrent releases

- .github/workflows/actionlint.yml
- .github/workflows/ci.yml
- .github/workflows/copy-pr-template-to-dependabot-prs.yml
We agree that pinning the versions of GitHub Actions actions to a commit hash
instead of a mutable tag is the correct choice.
We have a lot of places where we use them. The changes in this commit were
generated by using a tool called pinact[1] which can convert pinned tags in GHA
workflows to the commit hash they point to at that moment in time.
To generate the change set I ran `pinact run` from the root of the repository.
[1] https://github.com/suzuki-shunsuke/pinact
> Globally pin GitHub Actions actions to commit hashes not tags
