config/routes.rb

Initial check to verify that sentry notifications are appearing as expected.

Test Sentry notifications

---

LICENCE
README.md

Add some basic info to the README and add LICENCE.
Trello: https://trello.com/c/kOuisVYY/547-8-provision-and-deploy-a-new-barebones-admin-app

Update README and add LICENCE

---

.rspec
Gemfile
Gemfile.lock
app/controllers/metrics_controller.rb
app/services/metrics_service.rb
app/views/metrics/show.html.erb
config/routes.rb
spec/features/single_content_item_spec.rb
spec/rails_helper.rb
spec/support/content_data_api.rb
startup.sh

Display an aggregated metric (unique page views) for a single content item

Display an aggregated metric (unique page views) for a single content item

---

config/initializers/govuk_publishing_components.rb

Update stylesheet path and application path for components guide.
**Note**
Haven't deployed the project, raised the PR judging by the paths. If someone can test this by checking `component-guide/chart` is rendering correctly would be great.

Enable assets for components guide

---

app/controllers/metrics_controller.rb
app/helpers/charts_helper.rb
app/presenters/chart_presenter.rb
app/services/metrics_service.rb
app/views/metrics/show.html.erb
spec/features/single_content_item_spec.rb
spec/presenters/chart_presenter_spec.rb
spec/support/content_data_api.rb

Format and render the time series data that we request from the cpm api
in order to populate the chart and table components.
This is the first iteration so the designs are not final but provides all the vital
data needed for these components.

Render metric timeseries data

---

app/assets/stylesheets/components/_chart.scss
app/views/components/_chart.html.erb
app/views/development/index.html.erb
spec/components/chart_spec.rb
spec/features/single_content_item_spec.rb

This adds the ability to tab to tables in order to allow keyboard
users to scroll, and makes a number of visual changes both to
improve them visually and to work better for assistive technology.
https://trello.com/c/jFjpCpUO/552-8-build-chart-component-depends-on-547
https://trello.com/c/Yg2DOlhE/674-charts-and-table-design-feedback

Update chart component with accessibility and design tweaks

---

app/views/components/_metadata.html.erb
app/views/components/_time-select.html.erb
app/views/metrics/show.html.erb
config/application.rb
config/locales/defaults/en.yml
config/locales/views/components/en.yml
config/locales/views/metrics/en.yml
spec/components/metadata_spec.rb
spec/features/single_content_item_spec.rb

This is an initial PR to use locales in the single page view. Locales have not used been *everywhere* as waiting for refactoring template partials.

Use locales in single page view

---

app/views/components/_info-metric.html.erb
app/views/metrics/_metric_header.html.erb
app/views/metrics/_metric_section.html.erb
app/views/metrics/show.html.erb
config/locales/defaults/en.yml
config/locales/views/metrics/en.yml
spec/components/info_metric_spec.rb

Adding a metric section partial to reduce code repetition in the single page view and enable locale use in graph metric overviews.

Add metric section partial

---

app/views/components/_info-metric.html.erb
config/locales/views/components/en.yml
spec/components/info_metric_spec.rb

Textual infomation around about this data is now render using locales.

Use locales in about this data section

---

app/views/components/_time-select.html.erb
app/views/metrics/_metric_section.html.erb
config/locales/views/components/en.yml
config/locales/views/metrics/en.yml

Remove unused locales and renamed locales to reflect latest design.

Cleanup locales

---

config/locales/views/metrics/en.yml

Superseds https://github.com/alphagov/content-data-admin/pull/98

Fix typo in edit link text

---

app/controllers/content_controller.rb
app/views/content/index.html.erb
spec/features/index_page_spec.rb

[This CPM PR](https://github.com/alphagov/content-performance-manager/pull/963) needs to be merged first.
Show the organisation that has been selected in the organisation dropdown.
So that users can see which organisation's content they are viewing.

Show selected org

---

app/controllers/application_controller.rb
app/models/user.rb
config/initializers/gds-sso.rb
db/migrate/20181023114343_create_users.rb
db/schema.rb
spec/factories/users.rb
spec/features/date_selection_spec.rb
spec/features/index_page_spec.rb
spec/features/single_content_item_spec.rb
spec/models/user_spec.rb

https://trello.com/c/0jIlqqCt/729-2-add-signon-users-to-content-data-admin

Configure GDS::SSO

---

config/locales/defaults/en.yml

Fixes spelling and wording of infomation about metrics to reflect the indended design.

Fix metric information in microcopy

---

app/assets/javascripts/core/filtertoggle.js
app/assets/stylesheets/content/_index.scss
app/views/development/index.html.erb

https://trello.com/c/2NUh4o8A/777-1-bug-fix-js
This shifts the call to the filter toggle js to make it exclusive to where it is needed, and removes 
the global call to application js as the gem covers this. It also adds some spacing to mobile
views.
Fixes js errors and tidies up views on narrow screens.
---
* [/ ] Added to trello card.

Fix javascript errors

---

app/controllers/content_controller.rb
app/helpers/pagination_helper.rb
app/presenters/content_items_presenter.rb
app/views/content/index.html.erb
spec/features/index_page_spec.rb
spec/helpers/pagination_helper_spec.rb
spec/presenters/content_items_presenter_spec.rb

This merges work of the frontend design (`/dev`) into the functional features in (`/content`). 
This is to bring our content page closer to the intended design.
---

Update index page to use latest design

---

app/presenters/content_row_presenter.rb
app/views/content/index.html.erb
spec/presenters/content_row_presenter_spec.rb

To make it easier to read.
---

Use comma separators for searches on index page

---

app/controllers/content_controller.rb
app/services/find_content.rb
app/views/content/index.html.erb
app/views/development/index.html.erb
lib/gds_api/content_data_api.rb
spec/features/index_filter_by_title_spec.rb
spec/support/content_data_api.rb

[Trello card](https://trello.com/c/l2T9VoVG/725-5-index-page-filter-by-title-url)
Adds filtering by title or URL to the index page.
There are no changes to the UI other than the filtering.

Add filter by title-url to the index page

---

app/views/components/_chart.html.erb
spec/components/chart_spec.rb
spec/features/date_selection_spec.rb
spec/features/single_content_item_spec.rb

https://trello.com/c/BcV95S5T/867-3-labels-on-charts-and-chart-tables-decide-on-date-labels-with-content-design-and-implement
Alter the date formats on both chart graphs and chart tables. Update tests to reflect changes.
Meet GDS standards, make data more easy to digest

Change date formats to meet GDS patterns, update tests 

---

app/assets/stylesheets/components/_chart.scss
app/assets/stylesheets/content/_index.scss
app/views/components/_chart.html.erb
app/views/content/index.html.erb
app/views/layouts/application.html.erb

1. Update chart tables visually
2. Scope CSS better
1. Match designs
2. Avoid future clashes of styles between pages
https://trello.com/c/6GiWaN7D/868-1-chart-table-visual-adjustments

Update chart table styles and add better scoping for css rules

---

app/views/layouts/application.html.erb
spec/features/index_page_spec.rb

For the "Send us feedback" link.
https://trello.com/c/EILNhFn1/903-2-publish-feedback-form-for-content-data-beta-in-the-support-app

Link to the Support app

---

db/seeds.rb

Now a user doesn't need to be manually created when running the
app in development mode.

Add user to db/seeds.rb

---

app/assets/javascripts/core/gtm.js
app/views/content/index.html.erb
app/views/metrics/show.html.erb

* Updates to GTM tracking to make custom events easier to use
* Make gtm.js script more resilient to elements not being present
* a few small style fixes.

GTM javascript v2

---

app/presenters/content_items_csv_presenter.rb
spec/presenters/content_items_csv_presenter_spec.rb

https://trello.com/c/yLoOoyUv/864-5-index-page-add-download-csv

CSV export fix URL and change some headings

---

app/views/components/_chart.html.erb

This data-attribute will help us fix the IE11 bug on selects

Add data-gtm attribute for table reveal tracking

---

app/assets/stylesheets/components/_chart.scss
app/views/components/_chart.html.erb

Colour changes on charts
https://trello.com/c/faZhfq6U/1007-1-change-colour-on-charts
Match designs better, add contrast.

Update chart colours to match design

---

config/locales/defaults/en.yml
spec/features/single_content_item_spec.rb

I changed short_title for feedback comments instead of about_title so I've fixed that.
PR #323

Fixes mistake in PR #323

---

spec/routing/content_routing_spec.rb
spec/routing/single_page_routing_spec.rb

Add addition test for `/content` routes and simplified tests for `/metrics` routes.
To complete coverage of route tests.
---

Improve routing specs

---

app/assets/stylesheets/components/_time-select.scss
app/assets/stylesheets/content/_index.scss
app/views/content/index.html.erb

https://trello.com/c/q8syn4ox/1088-1-adjust-inside-horizontal-and-vertical-padding-to-6-for-all-items-inside-the-filter-column
Increase spacing
Meet designs

Increase spacing between filter form elements

---

app/assets/stylesheets/content/_index.scss
app/controllers/content_controller.rb
app/helpers/table_header_helper.rb
app/models/sort.rb
app/presenters/content_items_presenter.rb
app/services/find_content.rb
app/views/content/index.html.erb
lib/gds_api/content_data_api.rb
spec/features/index_page/sorting_spec.rb
spec/features/index_page/user_analytics_spec.rb
spec/helpers/pagination_helper_spec.rb
spec/helpers/table_header_helper_spec.rb
spec/models/sort_spec.rb
spec/presenters/content_items_presenter_spec.rb
spec/support/content_data_api.rb
spec/support/request_stubs.rb

This PR adds functionality to sort by column in the results table on the content page.
Changes include:
- Adds sort class to capture behaviour relating to a sort parameter
- Adds table header helper to extract header formatting logic
- Fix to sort link styles
- Adds sort parameter as permitted parameter in content controller
- Adds sort parameter to Content Data API calls
- Adds related unit and feature tests
To make it easier for users to find content based on a particular metric value.
---

Results table sorting

---

Gemfile
Gemfile.lock

Reverts alphagov/content-data-admin#399

Revert "Bump govuk_publishing_components from 15.3.0 to 16.1.0"

---

app/assets/javascripts/application.js

Fix asset paths to get jquery working

Fix asset paths order

---

app/assets/stylesheets/content/_index.scss

Increase spacing on the table. Refactor redundant styles and tidy up table cell declarations.
https://trello.com/c/GmlNpF0Y/1182-2-table-column-and-cell-padding-adjustments
Match design, improve legibility of CSS

Alter spacing on table and remove redundant styles.

---

spec/features/index_page/user_analytics_spec.rb

This adds a feature test clicking the app name in the header.
We need to be sure we don't break tracking with Google Analytics.
---

Add feature tests for tracking clicking app name

---

app/assets/stylesheets/content/_index.scss
app/views/content/_page_title.html.erb

https://trello.com/c/sOjrLlpI/1245-1-make-all-links-inside-the-index-page-table-bold
Make links to data page bold
Updated/improved design

Make links to data page bold

---

app/services/concerns/content_data_api_client.rb
app/services/fetch_aggregated_metrics.rb
app/services/fetch_document_types.rb
app/services/fetch_organisations.rb
app/services/fetch_single_page.rb
app/services/fetch_time_series.rb
app/services/find_content.rb
app/services/metrics_common.rb
lib/gds_api/content_data_api.rb
spec/features/single_content_item_spec.rb

1. Remove a timeout that is no longer needed as per the performance reports
2. Remove duplicated block
3. Simplify API removing unused parameters
4. Extract concern to improve readability of interactions with Content Data Api

Refactor: simplify how we interact with services

---

app/assets/stylesheets/components/_related-actions.scss
app/views/components/_related-actions.html.erb
app/views/metrics/show.html.erb
config/locales/views/metrics/en.yml
spec/components/related_actions_spec.rb

https://trello.com/c/7s3wBwGs/1254-3-clean-up-action-links-on-the-page-data-page
- Remove headers
- Reword links
- Adjust styling
- Update related tests
Reduce space use, match updated design

Update action links

---

app/presenters/filter_presenter.rb

- Both functions do the same thing so having two different code styles is
confusing so refactoring makes it easier to understand
Trello: https://trello.com/c/xs0gSvRR
Refactoring code
Make code easier to understand
---

Refactor filter option functions

---

README.md

A few general README updates. 
---
* ~~Added/updated unit tests.~~
* ~~Added/updated feature tests.~~
* ~~Added to Trello card.~~

Update the Content Data Admin README

---

app/assets/stylesheets/metrics/_show.scss

https://trello.com/c/7XYi4Qfn/1476-change-the-first-line-in-the-page-content-table-from-2-pixels-to-1-pixel-thick
Make border line match design/other lines
Consistency

Tweak style to match design

---

app/presenters/single_content_item_presenter.rb
app/views/metrics/_content_metrics.html.erb
config/locales/defaults/en.yml
spec/features/single_content_item_spec.rb
spec/presenters/single_content_item_presenter_spec.rb

Renaming total_pdf_count to pdf_count for consistency.

Rename total_pdf_count to pdf_count

---

config/locales/defaults/en.yml

Explained where on GOV.UK the is this page useful survey is found. Also fixed a typo in about number of PDFs.
To give extra context for users who aren't familiar with the survey. 
---

Clarify text about users who found page useful

---

app/controllers/documents_controller.rb
app/services/fetch_document_children.rb
lib/gds_api/content_data_api.rb
spec/features/document_children_page/documents_children_page_spec.rb
spec/support/content_data_api.rb
spec/support/request_stubs.rb
spec/support/response_helpers.rb

This adds code to call the real backend api endpoint and removes the stubbed response. This also adds stubs for feature testing.
---

Remove stubbing of document children API call

---

app/controllers/documents_controller.rb
app/helpers/table_header_helper.rb
app/presenters/document_children_presenter.rb
app/views/documents/_table.html.erb
app/views/documents/children.html.erb
config/locales/views/documents/en.yml
spec/features/document_children_page/documents_children_page_spec.rb
spec/features/document_children_page/sorting_spec.rb

https://trello.com/c/f7JJpYlr/1521-fix-links-for-time-selection-on-comparison-page
https://trello.com/c/NCW7G67L/1525-implement-sorting-to-the-comparison-table-page
NB selecting from page params in views currently as I couldn't work out how to get
the presenter to interact with page parameters.

Make filters and sorts work

---

app/views/documents/_table.html.erb

Currently the sorted column isn't being highlighted due to a coding error, this fixes that.

Bugfix: enable highlight on sorted column

---

config/locales/defaults/en.yml

We are using data instead of metrics 
Because it's more comprehensible for users
---

Use 'data' instead of 'metrics'

---

config/locales/views/documents/en.yml
spec/features/document_children_page/documents_children_page_spec.rb
spec/features/single_content_item_spec.rb
spec/presenters/document_children_presenter_spec.rb
spec/routing/documents_routing_spec.rb
spec/support/request_stubs.rb

Comparison was misspelt comparision
---

Fix typo with the word comparison

---

Gemfile.lock
app/assets/config/manifest.js

Update to Sprockets 4

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/compare/_show.scss
app/assets/stylesheets/components/_ga_data_notice.scss
app/assets/stylesheets/content/_index.scss
app/views/components/_ga_data_notice.html.erb
app/views/content/export_csv.html.erb
app/views/content/index.html.erb
app/views/content_csv_mailer/content_csv_email.text.erb
app/views/documents/children.html.erb
app/views/metrics/show.html.erb
config/locales/defaults/en.yml

This is necessary to inform users of the app about changes with the data.
| Desktop  | Mobile |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1130010/71264754-ad41c500-233c-11ea-966e-49e702d36d08.png) | ![image](https://user-images.githubusercontent.com/1130010/71264821-d1050b00-233c-11ea-8a5e-fe4dc091a73f.png) |
| ![image](https://user-images.githubusercontent.com/1130010/71265279-c5661400-233d-11ea-9d45-7946f1d6c6d9.png) | ![image](https://user-images.githubusercontent.com/1130010/71265324-de6ec500-233d-11ea-86a9-1c97f8bf64c9.png) |
| ![image](https://user-images.githubusercontent.com/1130010/71264889-f6921480-233c-11ea-98f9-ac3dfb6f22f0.png) | ![image](https://user-images.githubusercontent.com/1130010/71264904-ff82e600-233c-11ea-89aa-ce48fdc4fd9d …

Add a notice about Google Analytics data

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_ga_data_notice.scss
app/assets/stylesheets/components/_related-actions.scss

Some small stylistic tweaks.
---

Small style changes

---

config/locales/defaults/en.yml

Fix typo in the Google Analtyics data warning

---

spec/rails_helper.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review

Always print SimpleCov report of code coverage

---

README.md

Add a note about CD to the readme

---

app/views/content/index.html.erb

Very minor, but broken HTML markup.

Fix broken markup

---

app/assets/javascripts/survey-banner/survey-banner.js

Deploy task fails because of ES6 syntax.

Don't use ES6 syntax in survey-banner script

---

app/presenters/single_content_item_presenter.rb
lib/gds_api/content_data_api.rb

Small additional cleanup of unused methods

Remove unused methods

---

.github/workflows/ci.yml

https://trello.com/c/BmET7H34/3326-add-dependabot-scan-to-ci-pipelines

add dependecy review to CI pipeline

---

app/views/content/export_csv.html.erb
app/views/content_csv_mailer/content_csv_email.text.erb

Amend support email

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js
app/assets/javascripts/application.js
app/assets/javascripts/es6-components.js
app/views/layouts/application.html.erb
config/environments/production.rb

https://trello.com/c/qmPB0DEN/3581-upgrade-our-apps-to-v51-of-the-design-system-3

Upgrade to govuk frontend 5.1
